### ISSUE TITLE
Date format escaping doesn't work

### ISSUE THREAD

**Issue by Kmaschta** [marnusw/date-fns-tz#10]
Say we have the following code at February 2019:

```js
const { format } = require('date-fns-tz');

format(new Date(), '[the] MM/YYYY');
```

The expected output is `02/2019`
The actual ouput is `[154963275526] 02/2019`

As explained on the `date-fns` documentation, the we should be able to escape a string in the date format with `[]`.

**Comment by marnusw** [comment]
This library is an extension of `date-fns@2.0.0-alpha` and follows the same format syntax. From https://date-fns.org/v2.0.0-alpha.27/docs/format:

> The characters wrapped between two single quotes characters (') are escaped.

This was changed from the v1 syntax you are using in v2.

If you cannot use the alpha v2 of `date-fns` and need support for v1 you might consider https://www.npmjs.com/package/date-fns-timezone.
