### ISSUE TITLE
please export tzParseTimezone

### ISSUE THREAD

**Issue by ahfarmer** [marnusw/date-fns-tz#100]
I've been looking for something that can tell me the offset of a given timezone in JavaScript. I see the code for it here, but it is not exported by `date-fns-tz` so I can't use it:
https://github.com/marnusw/date-fns-tz/blob/master/src/_lib/tzParseTimezone/index.js

This StackOverflow post shows that this is a useful feature for others as well:
https://stackoverflow.com/questions/36112774/calculate-the-utc-offset-given-a-timezone-string-in-javascript

Seems like such a waste to have this great feature in this library and not expose it. Thanks!

**Comment by jherdman** [comment]
I'd like to second this request.

**Comment by marnusw** [comment]
Thanks for pointing this out. See `getTimezoneOffset` in `v1.1.1`.
