### ISSUE TITLE
Could not use timezone string except `UTC` in unit test

### ISSUE THREAD

**Issue by huasambo** [marnusw/date-fns-tz#106]
Everything works on fine on a react application, but all unit tests failed when use other timezone other than utc(has to be lowercase), for instance `America/New_York`

**Comment by chardielxr** [comment]
@huasambo This isn't an issue with this library, but general library support in Node. This can be resolved by leveraging the polyfill the lib author mentions in the README.md:

```
import IntlPolyfill from "intl";
import DateTimeFormatTimezonePolyfill from "date-time-format-timezone";

const setupTests = () => {
  if (global.Intl) {
    Intl.NumberFormat = IntlPolyfill.NumberFormat;
    Intl.DateTimeFormat = DateTimeFormatTimezonePolyfill;
```

**Comment by huasambo** [comment]
thanks @chardielxr
