### ISSUE TITLE
⚠️Bug: Output depends on local timezone

### ISSUE THREAD

**Issue by simlu** [marnusw/date-fns-tz#107]
I would expect below output to be consistent. Really not sure why it's not - feels like a bug.

If we're doing something wrong, I'd very much appreciate your help! Cheers

------------------

`test.js`
```
const { utcToZonedTime, format } = require('date-fns-tz');

const timeZone = 'America/Vancouver';
console.log(format(utcToZonedTime('2020-03-08T19:00:00.000Z', timeZone), 'yyyy-MM-dd hh mm', { timeZone }));

// export TZ=Australia/Adelaide && node test.js
// => 2020-03-08 11 00

// export TZ=UTC && node test.js
// => 2020-03-08 12 00
```

**Comment by ankit-gaur** [comment]
@simlu  when you to utcToZonedTime(input, tz) the output Date is having UTC value such that when you do date.getDate(),date.getHour(), date.getMinute() etc. these resolves to time in the tz you specified. So when you are formatting this time the corresponding utc value is getting converted to the timezone you specify to 'format' method but your input utc value is different when your system-timezones are different.

**Comment by simlu** [comment]
Any update on this?

**Comment by ankit-gaur** [comment]
I checked the code, the code doesn't take into account the timezone offset while parsing date string, it just extracts Y,M,D,H,M,S. 

this should work fine 

`console.log(format(utcToZonedTime(new Date('2020-03-08T19:00:00.000Z'), timeZone), 'yyyy-MM-dd hh mm', { timeZone }));`

**Comment by marnusw** [comment]
I haven't had time to look into this, but I can see that it is a serious problem. @ankit-gaur might be on to something, I'll take a look when I can. If anyone who needs this urgently could put some time toward this that would be great.

**Comment by simlu** [comment]
The workaround seems to work ok... however is there an ETA for a property fix?

**Comment by marnusw** [comment]
@simlu can you still reproduce this? Which version were you testing last?

I've tried to reproduce it now to no avail. I wonder if the issue might have been fixed in v1.1.2 which was released a few days after you opened this.

**Comment by marnusw** [comment]
Jip, I believe it was:

```
yarn add date-fns-tz@1.1.1

export TZ=Australia/Adelaide && node test.js
2020-03-08 11 00
export TZ=UTC && node test.js
2020-03-08 12 00

yarn add date-fns-tz@1.1.2

export TZ=Australia/Adelaide && node test.js
2020-03-08 12 00
export TZ=UTC && node test.js
2020-03-08 12 00
```

Please confirm whether you see the same on the most recent version.

**Comment by marnusw** [comment]
Please reopen if this is still an issue.

**Comment by simlu** [comment]
Was busy over the weekend, but will try to take a look today

**Comment by simlu** [comment]
Confirmed, seems fixed
