### ISSUE TITLE
Console output and toString/JSON.stringify on results from utcToZonedTime are confusing/wrong

### ISSUE THREAD

**Issue by tremby** [marnusw/date-fns-tz#109]
(split from https://github.com/marnusw/date-fns-tz/issues/94, updated, expanded)

I'm on v1.2.2, and `utcToZonedTime` is giving very confusing results when I experiment with it in a node console.

```
[bjn@spiral:~]$ node
Welcome to Node.js v14.15.4.
Type ".help" for more information.
> const { utcToZonedTime } = require("date-fns-tz");
undefined
> utcToZonedTime("2000-01-01", "Europe/London")
2000-01-01T16:00:00.000Z
> utcToZonedTime("2000-01-01Z", "Europe/London")
2000-01-01T08:00:00.000Z
> utcToZonedTime("2000-01-01", "Europe/Berlin")
2000-01-01T17:00:00.000Z
> utcToZonedTime("2000-01-01Z", "Europe/Berlin")
2000-01-01T09:00:00.000Z
>
```

First point of confusion: I expect a non-zoned time as input to be treated as UTC, since this function is called `utcToZonedTime`. So `utcToZonedTime("2000-01-01", "Europe/London")` and `utcToZonedTime("2000-01-01Z", "Europe/London")` ought to have the same results. As seen above, they come out with wildly different times.

Next, none of the results make sense to me. London's offset in January is 0, and Berlin's is +1. Midnight UTC therefore ought to be still midnight in London and 1am in Berlin. But I'm variously getting 4pm UTC, 8am UTC, 5pm UTC, 9am UTC, none of which are the midnight UTC I asked for no matter which way you look at it, and none of 4pm or 8am London time, or 5pm or 9am Berlin time are accurate either. 

Next, the function is called `utcToZonedTime` but all the results are saying they're in UTC time (the `Z` suffix).

Next, if I run `.toString()` on the result, I get the same time shifted to my own local time zone:

```
> utcToZonedTime("2000-01-01Z", "Europe/London").toString()
'Sat Jan 01 2000 00:00:00 GMT-0800 (Pacific Standard Time)'
> utcToZonedTime("2000-01-01Z", "Europe/Berlin").toString()
'Sat Jan 01 2000 01:00:00 GMT-0800 (Pacific Standard Time)'
```

But midnight UTC is not at all midnight or 1am in Pacific time, so these results are just as confusing.

I recognize this output as a probable clue to how the library works -- it's as if it's pretending my local timezone is UTC, and making calculations relative to that. What confuses me is, what exactly is "zoned" about the result of this function? Is this expected behaviour? If so, perhaps at least some much clearer documentation would help. It definitely scared me away from using the library.

**Comment by bggolding** [comment]
I’m trying to convert from UTC (which we use in our db) to local time but the time difference seems to go backwards instead of forwards. I wrote a little test:

```
it("should make the time local", () => {
    const t_utc = "2021-04-01T06:00:00.000000";
    const t_au  = "2021-04-01T17:00:00.000000";

    expect(tzName).toEqual("Australia/Melbourne");
    expect(utcToZonedTime(t_utc, tzName)).toEqual(t_au);
}
```

And the output I get is:
```
Error: expect(received).toEqual(expected) // deep equality

Expected: "2021-04-01T17:00:00.000000"
Received: 2021-03-31T19:00:00.000Z
Expected :2021-04-01T17:00:00.000000
```
which looks just like UTC-10 instead of UTC+10. Am I doing something wrong?

**Comment by ankit-gaur** [comment]
@tremby  there is a bug in the parsing logic of utcToZonedTime method, you should be passing a Date object to be on safe side. Other than that one, look at this discussion to know how date-fns-tz actually work, https://github.com/marnusw/date-fns-tz/issues/118

**Comment by ankit-gaur** [comment]
https://github.com/marnusw/date-fns-tz/issues/107

**Comment by marnusw** [comment]
@bggolding your problem is that you're using

```js
const t_utc = "2021-04-01T06:00:00.000000";
```

which is, in fact, not a UTC time because there is no time zone info in the string. Thus, when the string is converted to a `Date` it is done in the machine's local time. From there all further work will be wrong.

If you use

```js
const t_utc = "2021-04-01T06:00:00.000Z";
```

Then everything should work as expected.

**Comment by marnusw** [comment]
@tremby after using `utcToZonedTime` the internal timestamp of the date would have changed to make the date resemble being in a different time zone when formatted. 

Thus for the result `.toISOString()` will be invalid, and printing directly to console will usualy result in confusing output. The best option is to use the `format` function from the library to look at the output.

If you want to get a proper UTC time back from `.toISOString()` / `JSON.stringify` again, use `zonedTimeToUtc` first to reverse the initial operation.

**Comment by tremby** [comment]
I barely understood a word of that. Can you put it in terms of my original examples, please?
