### ISSUE TITLE
DD format is day of the year instead of the date of the month

### ISSUE THREAD

**Issue by Kmaschta** [marnusw/date-fns-tz#11]
Say we have the following code February the 8th 2019:

```js
const { format } = require('date-fns-tz');

format(new Date(), 'DD');
```

The expected output is `08`
The actual ouput is `51`

**Comment by marnusw** [comment]
This library is an extension of `date-fns@2.0.0-alpha` and as such uses the same tokens for the year and day of month. You can refer to the `date-fns` documentation for further information and their use of standardised Unicode Tokens:

https://date-fns.org/v2.0.0-alpha.27/docs/format
https://date-fns.org/v2.0.0-alpha.27/docs/Unicode-Tokens

The readme has been updated to reflect the use of `yyyy-MM-dd` which was incorrect before.

If you cannot use the alpha v2 of `date-fns` and need support for v1 you might consider https://www.npmjs.com/package/date-fns-timezone.
