### ISSUE TITLE
Version 1.1.2 breaks IE11 support

### ISSUE THREAD

**Issue by Pierre-Do** [marnusw/date-fns-tz#112]
Hey,

As highlighted here (https://github.com/marnusw/date-fns-tz/commit/e97b76c41a772342149394f0cbe8b9a0042c553f#r47405922), the usage of a destructuring assignment yields an error with Internet Explorer 11.

## Steps to reproduce

* Import `date-fns-tz` at version 1.1.2 in a project
* Compile with IE11 support
* Open the page with IE11

For instance: 

![image](https://user-images.githubusercontent.com/1904504/109614012-461fc300-7b32-11eb-92ec-53ae9b3d020d.png)

The error is reported at this line (from the compiled bundle, at 85).

![image](https://user-images.githubusercontent.com/1904504/109614072-63549180-7b32-11eb-9f0e-0bc8228e2fd4.png)

We can see that we have a [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), unfortunately not supported by IE11.

**Comment by ondrasak** [comment]
That is not necessarily an issue of this library (it's OK if they decide to not support old browsers)

You can configure your module bundler (probably Webpack) in a way that this package will be processed to the desired format)

inspiration:
https://medium.com/slido-dev-blog/transpile-debug-and-other-npm-packages-to-es5-5acd87a087c2

**Comment by Aymkdn** [comment]
Same issue here.

Could you share how you fixed it?

**Comment by antch** [comment]
@Aymkdn Just a tip, I highly recommend using [patch-package](https://github.com/ds300/patch-package) to apply patches to npm modules rather than manually-editing the files, this will ensure that the change gets applied each time you `npm i`.

**Comment by Aymkdn** [comment]
> @Aymkdn Just a tip, I highly recommend using [patch-package](https://github.com/ds300/patch-package) to apply patches to npm modules rather than manually-editing the files, this will ensure that the change gets applied each time you `npm i`.

Thanks! I didn't know about it :)

> Is this the only line in the entire project which doesn't work in IE11? If so it could be changed. Ideally we should support all browsers `date-fns` does, and I'd assume they support IE11.

Yes, it is.
