### ISSUE TITLE
[ReferenceError: Can't find variable: Intl] when calling utcToZonedTime

### ISSUE THREAD

**Issue by odedmagger** [marnusw/date-fns-tz#114]
On my React Native / Typescript, project, I'm calling the following:
`utcToZonedTime(new Date(), "America/New_York")`

This yields the following exception: `ReferenceError: Can't find variable: Intl`
`

I have installed version 1.1.3 of `date-fns-tz` through yarn.
I am running the RN app on an Android, OS version 10.

**Comment by matt-dalton** [comment]
I'm also having the same issue

**Comment by anandchakru** [comment]
If you have enabled Hermes, if you have something like this in build.gradle
```js
project.ext.react = [
    enableHermes: true,
]
```
Ref this [sof](https://stackoverflow.com/a/65581430/234110) answer

If you have **not** enabled Hermes, in build.gradle, change
`def jscFlavor = 'org.webkit:android-jsc:+'`
to
`def jscFlavor = 'org.webkit:android-jsc-intl:+'`

**Note:** You will have to enable Hermes if you are using [reactnavigation](reactnavigation.org). It uses [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/installation/#android) and reanimated needs Hermes enabled

**Comment by matt-dalton** [comment]
Thanks @anandchakru! Quick clarification on that - why does setting `def jscFlavor = 'org.webkit:android-jsc-intl:+'` affect Hermes? Could you not use that fix and still use Hermes, rather than installing the JS module?

**Comment by anandchakru** [comment]
@matt-dalton refer issue [#29141](https://github.com/facebook/react-native/issues/29141)

**Comment by matt-dalton** [comment]
Ahh interesting. Because I'd imagine npm installing the dependency would increase app load time, whereas I suspect the android solution would just impact the bundle download size, which would be preferable for us I think. Guess will have to wait for that RN issue to be resolved.

**Comment by marnusw** [comment]
I've always used polyfills in React Native apps. The FormatJS one works very well and is actively maintained by Yahoo I believe. https://formatjs.io/docs/polyfills.

Either way, feel free to continue the discussion and if there is finally a RN solution that doesn't require a polyfill we can update the docs. I'll close this, though, since it's not actually a problem with this library.
