### ISSUE TITLE
Ability to get a list of all timeZones?

### ISSUE THREAD

**Issue by tar-aldev** [marnusw/date-fns-tz#122]
With this library, is it possible to get a list of all timzeones?

E.g. in your examples there are some like
```
const result = getTimezoneOffset('Africa/Johannesburg')
```

instead of putting a string, could I somehow use a variable from the library which corresponds to 'Africa/Johannesburg'?
Use Case:
Let's say there is a select with a list of timezones. Although I could just create array of timezones myself, I would have much more confidence if I could import this list from `date-fns-tz`; It means that if anything is changed inside the library, this list of timezones would be updated as well. Also it would ensure that it is working fine and is taking expected time zone name.

**Comment by cureau** [comment]
date-fns-tz doesn't store timezones, so I believe you have to store it locally or fetch them via an API.

Since a basic timezone string (e.g., `Europe/London`) can be used as a method param, you basically need a list of strings.

User's local timezone from the browser API: `Intl.DateTimeFormat().resolvedOptions().timeZone (user's local timezone for instance`

You can use this directly with the date-fns-lib

Attached to the bottom is an array to match all of Chrome's timezone strings in the same format. You could enrich and order this list fairly easily with something like the following. (You can also search the web for a json with the offsets stored alongside the strings — the downside is that some of these values change over time with laws and regulation (hopefully the strings themselves change less).

```
			let orderedTimes = [];
			_.forEach(this.tzStrings2, str => {

				// converted from date fns milliseconds
				const utcOffset = getTimezoneOffset(str);
				const hours = utcOffset / (60 * 60 * 1000);

				let adjusted = '';
				if (hours > 0) {
					adjusted = '+' + hours;
				} else if (hours < 0) {
					adjusted = hours;
				}

				let ret = {
					label: str + ' (UTC' + adjusted + ')',
					hours: hours,
					value: str
				};

				orderedTimes.push(ret);

			});

```

---

List of timezone strings:

`
			tzStrings2: [
				'Europe/Andorra',
				'Asia/Dubai',
				'Asia/Kabul',
				'Europe/Tirane',
				'Asia/Yerevan',
				'Antarctica/Casey',
				'Antarctica/Davis',
				'Antarctica/DumontDUrville', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
				'Antarctica/Mawson',
				'Antarctica/Palmer',
				'Antarctica/Rothera',
				'Antarctica/Syowa',
				'Antarctica/Troll',
				'Antarctica/Vostok',
				'America/Argentina/Buenos_Aires',
				'America/Argentina/Cordoba',
				'America/Argentina/Salta',
				'America/Argentina/Jujuy',
				'America/Argentina/Tucuman',
				'America/Argentina/Catamarca',
				'America/Argentina/La_Rioja',
				'America/Argentina/San_Juan',
				'America/Argentina/Mendoza',
				'America/Argentina/San_Luis',
				'America/Argentina/Rio_Gallegos',
				'America/Argentina/Ushuaia',
				'Pacific/Pago_Pago',
				'Europe/Vienna',
				'Australia/Lord_Howe',
				'Antarctica/Macquarie',
				'Australia/Hobart',
				'Australia/Currie',
				'Australia/Melbourne',
				'Australia/Sydney',
				'Australia/Broken_Hill',
				'Australia/Brisbane',
				'Australia/Lindeman',
				'Australia/Adelaide',
				'Australia/Darwin',
				'Australia/Perth',
				'Australia/Eucla',
				'Asia/Baku',
				'America/Barbados',
				'Asia/Dhaka',
				'Europe/Brussels',
				'Europe/Sofia',
				'Atlantic/Bermuda',
				'Asia/Brunei',
				'America/La_Paz',
				'America/Noronha',
				'America/Belem',
				'America/Fortaleza',
				'America/Recife',
				'America/Araguaina',
				'America/Maceio',
				'America/Bahia',
				'America/Sao_Paulo',
				'America/Campo_Grande',
				'America/Cuiaba',
				'America/Santarem',
				'America/Porto_Velho',
				'America/Boa_Vista',
				'America/Manaus',
				'America/Eirunepe',
				'America/Rio_Branco',
				'America/Nassau',
				'Asia/Thimphu',
				'Europe/Minsk',
				'America/Belize',
				'America/St_Johns',
				'America/Halifax',
				'America/Glace_Bay',
				'America/Moncton',
				'America/Goose_Bay',
				'America/Blanc-Sablon',
				'America/Toronto',
				'America/Nipigon',
				'America/Thunder_Bay',
				'America/Iqaluit',
				'America/Pangnirtung',
				'America/Atikokan',
				'America/Winnipeg',
				'America/Rainy_River',
				'America/Resolute',
				'America/Rankin_Inlet',
				'America/Regina',
				'America/Swift_Current',
				'America/Edmonton',
				'America/Cambridge_Bay',
				'America/Yellowknife',
				'America/Inuvik',
				'America/Creston',
				'America/Dawson_Creek',
				'America/Fort_Nelson',
				'America/Vancouver',
				'America/Whitehorse',
				'America/Dawson',
				'Indian/Cocos',
				'Europe/Zurich',
				'Africa/Abidjan',
				'Pacific/Rarotonga',
				'America/Santiago',
				'America/Punta_Arenas',
				'Pacific/Easter',
				'Asia/Shanghai',
				'Asia/Urumqi',
				'America/Bogota',
				'America/Costa_Rica',
				'America/Havana',
				'Atlantic/Cape_Verde',
				'America/Curacao',
				'Indian/Christmas',
				'Asia/Nicosia',
				'Asia/Famagusta',
				'Europe/Prague',
				'Europe/Berlin',
				'Europe/Copenhagen',
				'America/Santo_Domingo',
				'Africa/Algiers',
				'America/Guayaquil',
				'Pacific/Galapagos',
				'Europe/Tallinn',
				'Africa/Cairo',
				'Africa/El_Aaiun',
				'Europe/Madrid',
				'Africa/Ceuta',
				'Atlantic/Canary',
				'Europe/Helsinki',
				'Pacific/Fiji',
				'Atlantic/Stanley',
				'Pacific/Chuuk',
				'Pacific/Pohnpei',
				'Pacific/Kosrae',
				'Atlantic/Faroe',
				'Europe/Paris',
				'Europe/London',
				'Asia/Tbilisi',
				'America/Cayenne',
				'Africa/Accra',
				'Europe/Gibraltar',
				'America/Godthab',
				'America/Danmarkshavn',
				'America/Scoresbysund',
				'America/Thule',
				'Europe/Athens',
				'Atlantic/South_Georgia',
				'America/Guatemala',
				'Pacific/Guam',
				'Africa/Bissau',
				'America/Guyana',
				'Asia/Hong_Kong',
				'America/Tegucigalpa',
				'America/Port-au-Prince',
				'Europe/Budapest',
				'Asia/Jakarta',
				'Asia/Pontianak',
				'Asia/Makassar',
				'Asia/Jayapura',
				'Europe/Dublin',
				'Asia/Jerusalem',
				'Asia/Kolkata',
				'Indian/Chagos',
				'Asia/Baghdad',
				'Asia/Tehran',
				'Atlantic/Reykjavik',
				'Europe/Rome',
				'America/Jamaica',
				'Asia/Amman',
				'Asia/Tokyo',
				'Africa/Nairobi',
				'Asia/Bishkek',
				'Pacific/Tarawa',
				'Pacific/Enderbury',
				'Pacific/Kiritimati',
				'Asia/Pyongyang',
				'Asia/Seoul',
				'Asia/Almaty',
				'Asia/Qyzylorda',
				'Asia/Qostanay', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
				'Asia/Aqtobe',
				'Asia/Aqtau',
				'Asia/Atyrau',
				'Asia/Oral',
				'Asia/Beirut',
				'Asia/Colombo',
				'Africa/Monrovia',
				'Europe/Vilnius',
				'Europe/Luxembourg',
				'Europe/Riga',
				'Africa/Tripoli',
				'Africa/Casablanca',
				'Europe/Monaco',
				'Europe/Chisinau',
				'Pacific/Majuro',
				'Pacific/Kwajalein',
				'Asia/Yangon',
				'Asia/Ulaanbaatar',
				'Asia/Hovd',
				'Asia/Choibalsan',
				'Asia/Macau',
				'America/Martinique',
				'Europe/Malta',
				'Indian/Mauritius',
				'Indian/Maldives',
				'America/Mexico_City',
				'America/Cancun',
				'America/Merida',
				'America/Monterrey',
				'America/Matamoros',
				'America/Mazatlan',
				'America/Chihuahua',
				'America/Ojinaga',
				'America/Hermosillo',
				'America/Tijuana',
				'America/Bahia_Banderas',
				'Asia/Kuala_Lumpur',
				'Asia/Kuching',
				'Africa/Maputo',
				'Africa/Windhoek',
				'Pacific/Noumea',
				'Pacific/Norfolk',
				'Africa/Lagos',
				'America/Managua',
				'Europe/Amsterdam',
				'Europe/Oslo',
				'Asia/Kathmandu',
				'Pacific/Nauru',
				'Pacific/Niue',
				'Pacific/Auckland',
				'Pacific/Chatham',
				'America/Panama',
				'America/Lima',
				'Pacific/Tahiti',
				'Pacific/Marquesas',
				'Pacific/Gambier',
				'Pacific/Port_Moresby',
				'Pacific/Bougainville',
				'Asia/Manila',
				'Asia/Karachi',
				'Europe/Warsaw',
				'America/Miquelon',
				'Pacific/Pitcairn',
				'America/Puerto_Rico',
				'Asia/Gaza',
				'Asia/Hebron',
				'Europe/Lisbon',
				'Atlantic/Madeira',
				'Atlantic/Azores',
				'Pacific/Palau',
				'America/Asuncion',
				'Asia/Qatar',
				'Indian/Reunion',
				'Europe/Bucharest',
				'Europe/Belgrade',
				'Europe/Kaliningrad',
				'Europe/Moscow',
				'Europe/Simferopol',
				'Europe/Kirov',
				'Europe/Astrakhan',
				'Europe/Volgograd',
				'Europe/Saratov',
				'Europe/Ulyanovsk',
				'Europe/Samara',
				'Asia/Yekaterinburg',
				'Asia/Omsk',
				'Asia/Novosibirsk',
				'Asia/Barnaul',
				'Asia/Tomsk',
				'Asia/Novokuznetsk',
				'Asia/Krasnoyarsk',
				'Asia/Irkutsk',
				'Asia/Chita',
				'Asia/Yakutsk',
				'Asia/Khandyga',
				'Asia/Vladivostok',
				'Asia/Ust-Nera',
				'Asia/Magadan',
				'Asia/Sakhalin',
				'Asia/Srednekolymsk',
				'Asia/Kamchatka',
				'Asia/Anadyr',
				'Asia/Riyadh',
				'Pacific/Guadalcanal',
				'Indian/Mahe',
				'Africa/Khartoum',
				'Europe/Stockholm',
				'Asia/Singapore',
				'America/Paramaribo',
				'Africa/Juba',
				'Africa/Sao_Tome',
				'America/El_Salvador',
				'Asia/Damascus',
				'America/Grand_Turk',
				'Africa/Ndjamena',
				'Indian/Kerguelen',
				'Asia/Bangkok',
				'Asia/Dushanbe',
				'Pacific/Fakaofo',
				'Asia/Dili',
				'Asia/Ashgabat',
				'Africa/Tunis',
				'Pacific/Tongatapu',
				'Europe/Istanbul',
				'America/Port_of_Spain',
				'Pacific/Funafuti',
				'Asia/Taipei',
				'Europe/Kiev',
				'Europe/Uzhgorod',
				'Europe/Zaporozhye',
				'Pacific/Wake',
				'America/New_York',
				'America/Detroit',
				'America/Kentucky/Louisville',
				'America/Kentucky/Monticello',
				'America/Indiana/Indianapolis',
				'America/Indiana/Vincennes',
				'America/Indiana/Winamac',
				'America/Indiana/Marengo',
				'America/Indiana/Petersburg',
				'America/Indiana/Vevay',
				'America/Chicago',
				'America/Indiana/Tell_City',
				'America/Indiana/Knox',
				'America/Menominee',
				'America/North_Dakota/Center',
				'America/North_Dakota/New_Salem',
				'America/North_Dakota/Beulah',
				'America/Denver',
				'America/Boise',
				'America/Phoenix',
				'America/Los_Angeles',
				'America/Anchorage',
				'America/Juneau',
				'America/Sitka',
				'America/Metlakatla',
				'America/Yakutat',
				'America/Nome',
				'America/Adak',
				'Pacific/Honolulu',
				'America/Montevideo',
				'Asia/Samarkand',
				'Asia/Tashkent',
				'America/Caracas',
				'Asia/Ho_Chi_Minh',
				'Pacific/Efate',
				'Pacific/Wallis',
				'Pacific/Apia',
				'Africa/Johannesburg'
			]
```

**Comment by maacpiash** [comment]
Moment.js has this feature: https://momentjs.com/timezone/docs/#/data-loading/getting-zone-names/

Sad to see that `date-fns-tz` doesn't have this feature. Now I have to add Moment.js to my project only for this purpose!

**Comment by marnusw** [comment]
`date-fns-tz` is a wrapper for the Intl API, nothing more.

**Comment by marnusw** [comment]
Well, if you can get an API added to the Intl API which provides this information we can use it. Until then, comments like these aren't particularly useful.

**Comment by augnustin** [comment]
My comment is not particularly useful, but [yours](https://github.com/marnusw/date-fns-tz/issues/122#issuecomment-888922531) neither.

I guess you are more aware of the existence of such API, since you maintain the repo? Or even consider creating an issue over chromium browser or something if it doesn't already?

**Comment by danielmarcano** [comment]
In case this helps anyone who comes to this thread, here's how we can obtain all timezones with the `Intl` API:



```ts
const timeZones = Intl.supportedValuesOf('timeZone');
```

You can read more about it in [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf).
