### ISSUE TITLE
Wrong startOfDay for the timezone 

### ISSUE THREAD

**Issue by andreys75** [marnusw/date-fns-tz#124]
```
date = utcToZonedTime(1492437600, "America/Noronha"); //Monday April 17, 2017 12:00:00 (pm) in time zone America/Noronha (-02)

_startOfDay = startOfDay(date).getTime()/1000;// 1492380000:  Sunday April 16, 2017 20:00:00 (pm) in time zone America/Noronha (-02)
```

**Comment by devcauldron** [comment]
Yeah, I assumed this, too would work, but `startOfDay` in `date-fns` is not timezone aware, so it uses the local time and it says it in the [documentation for the function](https://date-fns.org/v2.22.1/docs/startOfDay):

> **Description**
> Return the start of a day for the given date. The result will be in the local timezone.

**Comment by marnusw** [comment]
Correct me if I'm wrong, but isn't this what you're after:

```js
const zonedDate = utcToZonedTime(1492437600000, "America/Noronha")

const startOfZonedDate = startOfDay(zonedDate)

format(startOfZonedDate, 'yyyy-MM-dd HH:mm:ss.SSS')
// 2017-04-17 00:00:00.000
// which is correct

const date = zonedTimeToUtc(startOfZonedDate, "America/Noronha")
date.toISOString()
// 2017-04-17T02:00:00.000Z
date.getTime()/1000
// 1492394400
// which (I think) is also the desired UTC time isn't it?
```

In order to use the date as if it's in a specific time zone, shift it to that time zone, apply the intended function, shift it back to get the proper UTC time again.
