### ISSUE TITLE
Silent parse errors of time field

### ISSUE THREAD

**Issue by edemaine** [marnusw/date-fns-tz#125]
I recently noticed that I forgot a zero in one of my times, and it's silently ignored by `date-fns-tz`'s `toDate` and `utcToZonedTime`:
```js
{ toDate, utcToZonedTime } = require('date-fns-tz');
console.log(toDate('2021-06-05T9:00'));
console.log(utcToZonedTime('2021-06-05T9:00'));
// 2021-06-05T00:00:00.000Z
console.log(toDate('2021-06-05T09:00'));
console.log(utcToZonedTime('2021-06-05T09:00'));
// 2021-06-05T09:00:00.000Z
```

This makes some sense, but is also prone to mistake. By contrast, `date-fns` v2 fails to parse:
```js
parseISO = require('date-fns/parseISO');
console.log(parseISO('2021-06-05T9:00'));
// Invalid Date
console.log(parseISO('2021-06-05T09:00'));
// 2021-06-05T09:00:00.000Z
```

Maybe this is automatically part of the v2 redesign (#36)?

**Comment by ankit-gaur** [comment]
Avoid passing string to utcTozonedtime method its buggy, pass Date object instead. https://github.com/marnusw/date-fns-tz/issues/107

**Comment by marnusw** [comment]
In version 2 of the library `toDate` will go away and be replaced with wrappers of `parse` and `parseISO` from `date-fns`. For this reason I won't be adding these checks now.
