### ISSUE TITLE
Getting cloneObject error

### ISSUE THREAD

**Issue by pnvhuy** [marnusw/date-fns-tz#13]
Getting compilation error in version 1.0.7

Failed to compile.
./node_modules/date-fns-tz/esm/zonedTimeToUtc/index.js
Module not found: Error: Can't resolve 'date-fns/esm/_lib/cloneObject' in '/Users/{path}/node_modules/date-fns-tz/esm/zonedTimeToUtc'

**Comment by marnusw** [comment]
@pnvhuy will you please confirm whether you are using `date-fns` version 2 which is currently in alpha? This library will only work with v2. If so, please let me know which exact version of `date-fns` you are using so I can investigate.

**Comment by ioness** [comment]
Hello Marnusw, I had this same problem, after installing the 2.0.0 it all worked out. I havea question and I got to confess I am kind of a noob.

Is it a reasonable thing to use this package in production ?

**Comment by marnusw** [comment]
Yes @ioness, `date-fns` v2 is quite stable by now and we use both it and `date-fns-tz` in production on a number projects.

**Comment by ioness** [comment]
Thanks a lot for your opensource contribution, it's awesome!
