### ISSUE TITLE
TimeZone not displaying correctly when using zzz

### ISSUE THREAD

**Issue by vikalpjain** [marnusw/date-fns-tz#132]
I'm trying to format time to the user's timezone information. I'm using date-fns and date-fns-tz libraries to do that. Below is the code and output:

```
const utcToZonedTime = require('date-fns-tz/utcToZonedTime') 
const formatDate = require('date-fns-tz/format') 
const enGB = require('date-fns/locale/en-GB')

//tz is set to America/Los_Angeles
let tempDT = utcToZonedTime(new Date(classStartTime), tz)
tempDT = formatDate(tempDT, 'dd-MMM HH:mm a zzz', { timeZone: tz, locale: enGB})
console.log('tempDT', tempDT)
//This prints 13-Aug 07:30 AM GMT-7
```

What I need is 13-Aug 07:30 AM PST. When I use zzzz as timezone formatter, it does print the full name of timezone. But, short name is not working. What am I doing wrong?

**Comment by marnusw** [comment]
Perhaps the `en-GB` locale formats the TZ as GMT-7 rather than PST? Try using the `enUS` locale from date-fns instead and see if that fixes it.

This is a very unfortunate shortcoming of the Intl API which is out of the scope of this library.

**Comment by vikalpjain** [comment]
Sure, will try using enUS as locale. Are there any other workaround?

**Comment by marnusw** [comment]
No, the formatting depends on which locale is passed to the Intl date format. The best solution might be to pair a locale with each time zone so you always get the result you want. It's a bit silly, but it'll work. You don't actually need the full date-fns locale if this is all you use it for, it should be fine to just pass in `{ code: 'en-US' }` as the locale, for example, if I'm not mistaken.

**Comment by vikalpjain** [comment]
Tried this:
```
const temp1 = utcToZonedTime(new Date(), "US/Eastern");
console.log(
  format(temp1, "yyyy-mm-dd hh:mm:ss a zzz", {
    timeZone: "US/Eastern",
    "locale.code": "en-US"
  })
);
```
It still prints 2021-51-14 12:51:07 AM GMT-4 
:-(

**Comment by vikalpjain** [comment]
Also, noticed that same code works fine for some IANA time zone values. For example: 

```
const temp1 = utcToZonedTime(new Date(), "Europe/Paris");
console.log(
  format(temp1, "yyyy-mm-dd hh:mm:ss a zzz", {
    timeZone: "Europe/Paris",
    "locale.code": "enUS"
  })
);
```

prints 
2021-54-14 06:54:51 AM CEST
Makes me wonder, is it about finding the right IAMA names for the timezone?
