### ISSUE TITLE
isToday: extend date-fns to support checking isToday with a Time Zone

### ISSUE THREAD

**Issue by mfulton26** [marnusw/date-fns-tz#134]
I'd like to be able to use an extended `isToday` function to check to see if a `Date` occurs in a day given a specific Time Zone (and not using my computer's locale)

**Comment by marnusw** [comment]
I haven't thought to hard about it, but couldn't you just use `utcToZonedTime`?

```js
const zonedDate = utcToZonedTime(dateToCheck, timeZone)
isToday(zonedDate)
```

Since the `zonedDate` would format to the time in that time zone on your machine regardless of the machine locale I'd imagine `isToday` would also work.

**Comment by mfulton26** [comment]
that works; thank you
