### ISSUE TITLE
Incorrect getTimezoneOffset for 'America/Argentina', "date-fns-tz": "^1.1.6",

### ISSUE THREAD

**Issue by Romanior** [marnusw/date-fns-tz#137]
```
getTimeZoneOffset('America/Argentina')
-0
```

but
```
Argentina Standard Time
Time zone in Buenos Aires, Argentina (GMT-3)
```

MacOS 10.13.6
Chrome Browser.
Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by marnusw** [comment]
This is not enough information to diagnose your issue. The platform the Intl API runs on is key to know.

**Comment by Romanior** [comment]
Ok you can close the issue, there is no such timezone in IANA names only such zones

America/Argentina/Buenos_Aires 
America/Argentina/Catamarca 
America/Argentina/Cordoba
....

For them `getTimezoneOffset` works correctly
