### ISSUE TITLE
show timezone short code but don't localize date

### ISSUE THREAD

**Issue by rezaabedian** [marnusw/date-fns-tz#139]
Hi all,

We have a requirement to show date time in the users local date time, and to show the short code for the timezone.

Eg. `20-AUG-2021 09:00:00 (JST)`, so I am doing the following:

```
format(new Date(dateTimeUtc), 'dd-MMM-yyyy HH:mm:ss (zzz)', { locale: localeImportFromDateFns }
```

This returns:

`11-8月-2021 05:31:33 (JST)`, which is great! Except, we don't want MMM to also be localised. 

Does anyone know how to perform this partial localisation?

**Comment by marnusw** [comment]
Just format it as two separate strings and only pass the locale to the one formatting the time zone. Then join the strings afterward.
