### ISSUE TITLE
compatibility with ie11

### ISSUE THREAD

**Issue by klickagent** [marnusw/date-fns-tz#14]
new Intl.DateTimeFormat does not support different timezones in ie11. do you have any idea how to make it work in ie11?
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)

> timeZone
The time zone to use. The only value implementations must recognize is "UTC"; the default is the runtime's default time zone. Implementations may also recognize the time zone names of the IANA time zone database, such as "Asia/Shanghai", "Asia/Kolkata", "America/New_York".

thanks a lot

**Comment by dvlsg** [comment]
Have you tried the https://github.com/andyearnshaw/Intl.js/ polyfill yet?

**Comment by marnusw** [comment]
@klickagent the solution is to use a polyfill in IE11. I have used [Intl.js](https://github.com/andyearnshaw/Intl.js/) suggested by @dvlsg in this way successfully and you can also try [yahoo/date-time-format-timezone](https://github.com/yahoo/date-time-format-timezone) or [polyfill.io](https://polyfill.io).
