### ISSUE TITLE
format not printing the time in the selected timezone

### ISSUE THREAD

**Issue by lukasz-wronski** [marnusw/date-fns-tz#141]
No matter what timezone I choose format function returns the same value. Example below.

```
import { format } from 'date-fns-tz';

const date = new Date('Thu Oct 07 2021 15:22:48 GMT+0000')

console.log(format(date, "h:mm", { timeZone: "Europe/London" })) // prints 5:22
console.log(format(date, "h:mm", { timeZone: "America/New_York" })) // prints 5:22 as well
```

**Comment by hdoan-codaio** [comment]
+1 the idea of adding `formatTz`. I'm still wrapping my head around `utcToZonedTime` and `format`. For people who are unfamiliar with how DateTime work, the current behavior has been confusing to me as well.
