### ISSUE TITLE
format() is broken for Z, or examples in README are wrong

### ISSUE THREAD

**Issue by ex-nerd** [marnusw/date-fns-tz#146]
The README contains the following example:

```typescript
// When there is no offset in the date string the timeZone property is used
const bangkokDate = toDate('2014-10-25T13:46:20', { timeZone: 'Asia/Bangkok' })
format(bangkokDate, 'yyyy-MM-dd HH:mm:ssZ', { timeZone: 'Asia/Bangkok' }) // 2014-10-25 13:46:20+07:00
```

Attempting to compile this with `tsc` results in an error stating ``RangeError: Format string contains an unescaped latin alphabet character `Z` ``

This format string is also invalid when using `format` from `date-fns` so I suspect the example (and likely others) needs to be updated to escape the `'Z'`:

```typescript
// When there is no offset in the date string the timeZone property is used
const bangkokDate = toDate('2014-10-25T13:46:20', { timeZone: 'Asia/Bangkok' })
format(bangkokDate, "yyyy-MM-dd HH:mm:ss'Z'", { timeZone: 'Asia/Bangkok' }) // 2014-10-25 13:46:20+07:00
```

**Comment by marnusw** [comment]
Thanks. It should have been the `xxx` token in order to get the desired result. It will be fixed in the next release.
