### ISSUE TITLE
formatInTimeZone has incorrect typescript signature

### ISSUE THREAD

**Issue by rickpastoor** [marnusw/date-fns-tz#149]
It is defined like this: `function formatInTimeZone(date: Date | number, timeZone: string, options?: OptionsWithTZ): string`

But actually, it should be `date: Date | number, timeZone: string, format: string, options?: OptionsWithTZ` as far as I can see.

Am I missing something?

**Comment by pamartn** [comment]
Encountered same issue ... It seems there's no 'format' string parameter in `OptionsWithTZ` type either.

**Comment by marnusw** [comment]
This is the case in `v1.2.0`, but it was fixed in `v1.2.2` on 21 December.
