### ISSUE TITLE
`zonedTimeToUtc` does not accept timezone parameter as 00:00 in latest version.

### ISSUE THREAD

**Issue by gustavodamazio** [marnusw/date-fns-tz#156]
**Works** in version:
```json
{
    "date-fns": "2.28.0",
    "date-fns-tz": "1.1.7",
}
```
**Not Works** in version:
```json
{
    "date-fns": "2.28.0",
    "date-fns-tz": "1.2.2",
}
```

Code example:
```ts
import { zonedTimeToUtc } from 'date-fns-tz';

console.log(zonedTimeToUtc(new Date(), '00:00').getTime()) 
// In the version @date-fns-tz greater than or equal to "1.2.0" the result is NaN.
```

Is this the expected behavior?

**Comment by marnusw** [comment]
I don't think `00:00` is valid. I would guess it should be `+00:00`. If you have proof that it is a valid time zone offset I'll consider it a bug.

Feel free to submit a PR to fix it either way if it is a major issue for you. I'll accept the fix even if it is non-standard since it doesn't hurt.

**Comment by marnusw** [comment]
Closing since there was no response. I'm still happy to consider a PR adding this functionality.
