### ISSUE TITLE
utcToZonedTime not parsing UTC time EST properly

### ISSUE THREAD

**Issue by osamayawar** [marnusw/date-fns-tz#157]
I have UTC time that i would like to convert into EST

 `console.log(new Date(utcToZonedTime('2022-06-01T04:59:00', 'America/Toronto')))`

**Actual Output:** Wed Jun 01 2022 04:59:00 GMT-0400 (Eastern Daylight Time) 
**Expected Output:** Thur May 31 2022 23:59:00 GMT-0500 (Eastern Daylight Time)

FYI: EDT(GMT-4) starts from March and ends in September

**Comment by marnusw** [comment]
Please read the docs. You are not using the library correctly. There are some clear examples given.

**Comment by osamayawar** [comment]
Referring to the documentation (https://www.npmjs.com/package/date-fns-tz/v/1.1.6#utctozonedtime), i tried the following

- Using the format with timeZone & locale with utcToZonedTime
- Also tried using the "zzzz" unicode tokens and the short versions too.

Can you be a little more specific where should i look at and what i am missing?

**Comment by marnusw** [comment]
Is `'2022-06-01T04:59:00'` UTC time? Then please try

```js
const estDate = utcToZonedTime('2022-06-01T04:59:00' + 'Z', 'America/Toronto') // Or better yet create a Date instance to pass in
console.log(format(estDate, 'some date & tz format', { timeZone: 'America/Toronto' })) // You MUST use format to get the proper time zone output, console.log alone won't do
```

Or use the new shorthand `formatInTimeZone` similarly.

I've typed this from memory, I haven't tried it.
