### ISSUE TITLE
How to detect ambiguous dates in date-fns-tz

### ISSUE THREAD

**Issue by spierala** [marnusw/date-fns-tz#161]
When DST ends there are dates which "exist" twice. 

To detect if dates are ambiguous we had this util function which uses moment timezone:

```
function isAmbiguousDate(date: Date): boolean {
  if (date) {
      const zone: MomentZone = moment.tz.zone(timezone);
      const time: number = Date.UTC(
          date.getFullYear(),
          date.getMonth(),
          date.getDate(),
          date.getHours(),
          date.getMinutes()
      );
      const offsetOriginal: number = zone.parse(time);
      const offsetCheck: number = zone.parse(time + 3600000);

      return offsetOriginal < offsetCheck;
  }

  return false;
}
```

You can see the util function in action here:
https://stackblitz.com/edit/typescript-4mmzkx?file=index.ts
The util function compares the offset of a given timestamp with the offset of that timestamp + 1 hour.
The function works in any system timezone.

### Moment zone.parse
The moment timezone `zone.parse` returns the offset of an UTC constructed timestamp for a given timezone:
https://momentjs.com/timezone/docs/#/zone-object/parse/

### date-fns-tz getTimeZoneOffset
The function which sounds most similar in date-fns-tz is `getTimeZoneOffset`: https://github.com/marnusw/date-fns-tz#gettimezoneoffset

You can see my attempts using `getTimeZoneOffset` here: https://stackblitz.com/edit/typescript-3djtgo

The offsets look OK in system timezones which have no DST, e.g Perth/Australia:
![image](https://user-images.githubusercontent.com/1272446/153420558-ab1ab558-3c53-4a20-a0cf-303ffb424f3d.png)

But in a timezone which has DST, e.g. Brussels/Europe it looks like this:
![image](https://user-images.githubusercontent.com/1272446/153420908-2a51e930-205f-4352-978a-6d4d10f438d0.png)
I would expect to see a difference in the offsets similar to moment timezone.

So the question is: what is the equivalent of zone.parse in date-fns-tz? Or is there even a better way to detect "ambiguous" dates?

**Comment by spierala** [comment]
It seems to work when using `zonedTimeToUtc` on the first date before adding the extra hour.

```
function isAmbiguousDate(date: Date): boolean {
  if (date) {
      const dateZonedToUTC: Date = zonedTimeToUtc(date, timezone);
      const dateZonedToUTCPlus1H: Date = new Date(dateZonedToUTC.getTime() + 3600000);

      const offsetOriginal: number = getTimezoneOffset(timezone, dateZonedToUTC);
      const offsetCheck: number = getTimezoneOffset(timezone, dateZonedToUTCPlus1H);

      return offsetOriginal > offsetCheck;
  }

  return false;
}
```

See working example here:
https://stackblitz.com/edit/typescript-epc2pm?file=index.ts

Thanks for the super fast help!

**Comment by marnusw** [comment]
My pleasure. I'm glad you've found a solution.
