### ISSUE TITLE
Getting a list of timezones

### ISSUE THREAD

**Issue by matthew-dean** [marnusw/date-fns-tz#162]
Hi! How would I get a list of timezones using this library? Like, say I wanted to get a list of timezones in America to populate a `<select>`. What method would I call to do this?

**Comment by marnusw** [comment]
The library doesn't store a list of timezones. It depends on the timezones support by the Intl API implementation, and there isn't a function to retrieve that as far as I know. There might be a list of valid timezones on npm.

**Comment by matthew-dean** [comment]
I was able to get a list via this NPM library, in case anyone else encounters this, thanks! https://www.npmjs.com/package/@vvo/tzdb
