### ISSUE TITLE
formatInTimezone not working

### ISSUE THREAD

**Issue by timeisgolden** [marnusw/date-fns-tz#166]
Hi, team, I am facing an issue to display formatted date with timezone.
I used formatInTimeZone for this, but it didn't return the correct date with specific timezone.
below is my code.
```
import formatInTimeZone from 'date-fns-tz/formatInTimeZone';
formatInTimeZone(new Date(), 'America/New_York', 'MM/dd/yyyy hh:mm:ss aaaa');
```
result: `02/28/2022 12:45:35 p.m.`
it's returning based on my browser timezone instead above timezone.
expected result: `02/28/2022 11:45:35 a.m.`
Can anyone help me?

**Comment by JamesGelok** [comment]
Your code sample seems to have an error in it.

```ts
import formatInTimeZone from 'date-fns-tz/formatInTimeZone';
```

Should be 

```ts
import { formatInTimeZone } from 'date-fns-tz/formatInTimeZone';
```

**Comment by morningdew830** [comment]
I tested [Runkit](https://npm.runkit.com/date-fns-tz) and it looks working as intended.

**Comment by marnusw** [comment]
#172 has been closed. Is this an issue in the latest version?

**Comment by timeisgolden** [comment]
Thanks, @morningdew830 @marnusw 
I will close this issue because I solved it.
Thanks again.
