### ISSUE TITLE
formatInTimeZone "Europe/Paris" example crashes on Android

### ISSUE THREAD

**Issue by brownieboy** [marnusw/date-fns-tz#180]
The "Europe/Paris" `formatInTimeZone` example crashes on the Android emulator for me.  (I've not tried on an actual device as yet.)   Error is "Invalid time value", and it's thrown in this code:

```javascript
  if (!(0, _index.default)(originalDate)) {
    throw new RangeError('Invalid time value');
  } // Convert the date in system timezone to the same date in UTC+00:00 timezone.
```
which is at line 391 of file node_modules/date-fns/format/index.js.

I have a new, empty React Native project, created via `npx react-native init`.  I installed date-fns and date-fns-tz, then added this code to the main App.js file:

```javascript
// At the top
import {formatInTimeZone} from 'date-fns-tz';
import enGB from 'date-fns/locale/en-GB';

// further down
const App: () => Node = () => {
  const dateJS = new Date();
  const dateWithYearString = formatInTimeZone(
    dateJS,
    'Europe/Paris',
    'EEEE io MMMM yyyy',
    {
      locale: enGB,
    },
  );
  console.log(
    'TCL ~ file: App.js ~ line 74 ~ dateWithYearString',
    dateWithYearString,
  );
  const isDarkMode = useColorScheme() === 'dark';
``` 

Note: I've changed the format string from the example code on the Github repo, but the error triggers no matter what I seem to put for that.

Oddly enough, if I turn the React Native debugger on, it works okay, but then crashes when I turn the debugger off again.  That would normally point to some kind of a race condition, but I don't see how that's applicable here.

No issues on the iOS simulator.

**Comment by marnusw** [comment]
When you turn the debugger on the JavaScript is executed in the debugger and no longer on the phone, that is why it behaves differently. React Native on Android has trouble with the Intl API. Please see #59 and #179.

**Comment by brownieboy** [comment]
I didn't know that about the debugger, @marnusw .

Thanks for that tip, and for the links.  I don't know how I didn't find those when I searched the issues before posting (which I did, honest!).  I'll try the workarounds there.

**Comment by brownieboy** [comment]
One of the suggestions from #59 fixed it for me.

In app/build.gradle, change this:
```
// def jscFlavor = 'org.webkit:android-jsc:+'
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```

That caused a Java Heap Out of Memory error though.  I fixed by adding this to android/gradle.properties:
```
org.gradle.jvmargs=-Xmx2g -XX\:MaxHeapSize\=4g
```

**Comment by marnusw** [comment]
Thank you for sharing that.
