### ISSUE TITLE
'Invalid time zone specified' when calling formatInTimeZone with time zone offset and time zone tokens

### ISSUE THREAD

**Issue by patrik-csak** [marnusw/date-fns-tz#186]
Given the following documentation (emphasis mine):

> ### `formatInTimeZone`
>
> This function takes a `Date` instance in the system's local time or an ISO8601 string, and an IANA time zone name **or offset string**.

I expect the following to work:

```js
formatInTimeZone("1986-04-04T10:32:55.123Z", "+2", "dd.MM.yyyy HH:mm zzzz");
```

What actually happens:

```
RangeError: Invalid time zone specified: +2
    at new DateTimeFormat (<anonymous>)
    at getDTF (/home/runner/tmp-nodejs/node_modules/date-fns-tz/_lib/tzIntlTimeZoneName/index.js:36:10)
    at tzIntlTimeZoneName (/home/runner/tmp-nodejs/node_modules/date-fns-tz/_lib/tzIntlTimeZoneName/index.js:14:13)
    at Object.z (/home/runner/tmp-nodejs/node_modules/date-fns-tz/format/formatters/index.js:105:35)
    at /home/runner/tmp-nodejs/node_modules/date-fns-tz/format/index.js:344:75
    at Array.reduce (<anonymous>)
    at format (/home/runner/tmp-nodejs/node_modules/date-fns-tz/format/index.js:337:25)
    at formatInTimeZone (/home/runner/tmp-nodejs/node_modules/date-fns-tz/formatInTimeZone/index.js:41:30)
    at Object.<anonymous> (/home/runner/tmp-nodejs/index.js:4:13)
```

To reproduce, run the code in [this Replit Repl](https://replit.com/@ptrkcsk/date-fns-tz-formatInTimeZone-with-offset)

**Comment by ptrkcsk** [comment]
After a little more research, it looks like maybe it's not possible to convert a numerical offset to a named offset

**Comment by marnusw** [comment]
`'+02:00` should work.

**Comment by ptrkcsk** [comment]
Here you go! https://github.com/marnusw/date-fns-tz/pull/187

**Comment by dancornilov** [comment]
Hello, same issue with another time zone
```
const date  = new Date();

formatInTimeZone(date, 'Eastern Standard Time', 'yyyy-MM-dd HH:mm:ss zzz');
```

![image](https://user-images.githubusercontent.com/24212761/215779497-d2b2013b-86e2-46bb-a307-5b082c1cce11.png)

**Comment by marnusw** [comment]
Closing this, continued in #187.

**Comment by gunnartorfis** [comment]
Hey, we've been getting hundreds of Sentry errors related to this issue but are quite stuck on how to approach this. It seems like the time zone name is definitely in IANA. 

Our largest customer group is in Iceland and we've been getting:
`Invalid time zone specified: Atlantic/Reykjavik`

But also for 
- Europe/Lisbon
- Europe/Prague
- America/Mexico_City
- Africa/Johannesburg
- Asia/Katmandu
- Asia/Dubai

We're calling formatInTimezone based on the "company" timezone:
```ts
export const getCompanyTimezone = () => {
  const company = getCompany();

  const companyTimezone = company?.connections.location?.timeZone;

  if (companyTimezone && isValidTimezone(companyTimezone)) {
    return companyTimezone;
  }

  return getUserTimezone();
};
```

Here's the `isValidTimezone` function that has been implemented just for this issue, without any luck.
```ts
const isValidTimezone = (tz: string) => {
  if (!Intl?.DateTimeFormat().resolvedOptions().timeZone) {
    // This one has never been reported
    Sentry.captureException(new Error('Intl.DateTimeFormat().resolvedOptions().timeZone is undefined'), {
      extra: {
        tz,
        resolvedOptions: JSON.stringify(Intl.DateTimeFormat().resolvedOptions())
      }
    });
    return false;
  }

  try {
    Intl.DateTimeFormat(undefined, { timeZone: tz });
    return true;
  } catch (ex) {
    return false;
  }
};
```

I'm not sure how to approach this so any help is much appreciated ❤️

**Comment by jltxwesley** [comment]
Hey @gunnartorfis, did you end up solving this issue?

**Comment by brianpooe** [comment]
@gunnartorfis did you end up resolving this?

**Comment by brianpooe** [comment]
@marnusw i don't see a solution to the link attached to closing this issue. Is there a solution to this?
