### ISSUE TITLE
format: ISO dates with years between 0000 and 0099 parse to 1900-1999

### ISSUE THREAD

**Issue by tmeindle** [marnusw/date-fns-tz#188]
I believe the issue is here.
https://github.com/marnusw/date-fns-tz/blob/8dfeaa3e3531a41c00b291e8efa3b8b27faf7e09/src/utcToZonedTime/index.js#L36
passing in a  year 0 to 99 to the Date constructor results in it being parsed as 1900-1999.

Is this clone needed and if it is would updating it to:
return new Date(d.getTime())
work?

**Comment by marnusw** [comment]
Related to #185 so I will close this one.
