### ISSUE TITLE
_lib/convertToFP/index.js is missing

### ISSUE THREAD

**Issue by GU5TAF** [marnusw/date-fns-tz#20]
When using `formatWithOptions` from `date-fns-tz/fp` I get the following error `Cannot find module '../_lib/convertToFP/index.js'`. I've checked the installed module and it appears to be missing.

**Comment by jrista** [comment]
This is still an issue today...been trying to use the fp version of these functions and the currently published version of the library does seem to be missing something...

**Comment by marnusw** [comment]
Fixed in `1.0.8` via 5f736425875
