### ISSUE TITLE
"GMT" vs. "UTC"

### ISSUE THREAD

**Issue by raphaelschaad** [marnusw/date-fns-tz#201]
Does anyone know why `Intl.DateTimeFormat()` (date-fns-tz uses it, e.g., [here](https://github.com/marnusw/date-fns-tz/blob/4ced7b8b0a5aad5b08fc3a44476242c82bc3272d/src/_lib/tzIntlTimeZoneName/index.js#L35)) uses "GMT" instead of "UTC" in their formatted strings?

Skimming [the underlying ECMAScript spec](https://tc39.es/ecma402/#datetimeformat-objects), it's unclear to me.

[According to Wikipedia](https://en.wikipedia.org/wiki/Greenwich_Mean_Time#Time_zone), it seems "UTC" would be preferred when referring to a time offset.

**Comment by elvinasv** [comment]
I had to implement the solution showing `UTC` instead of `GMT`. Ended up using a custom function  
```ts
export const replaceGMTtoUTCformat = (date: string): string => {
    return typeof date === "string" ? date.replace("GMT", "UTC") : date;
};
```

**Comment by marnusw** [comment]
This library is beholden to the output of `Intl.DateTimeFormat`, so I will close this. I can say that in the UK Winter time is referred to as GMT, and not UTC. In that sense this is correct behaviour.
