### ISSUE TITLE
Timestamp strings with '[UTC]' tag are parsed by toDate function, but loose time info

### ISSUE THREAD

**Issue by jounaidr** [marnusw/date-fns-tz#203]
For example:

``` javascript
const date = toDate("2020-03-01T15:57:28Z[UTC]")

console.log(date.toString())
//will return: Sun Mar 01 2020 00:00:00 GMT+0000 (Greenwich Mean Time)
```
If the [UTC] bit of the string is removed, such as with `.replace(/\[.*]/, '')`, the time will not be lost. I believe strings like this should either parse with time intact or throw an exception.

**Comment by marnusw** [comment]
I'm not aware of a valid date format which puts UTC in square brackets; there is no provision for picking up on this in this library nor `date-fns`. The purpose of `toDate` is to make a best guess of the date provided, so I don't believe throwing an exception is the correct approach. If you know the format of the date string beforehand the `date-fns#parse` function might be a better choice.

**Comment by jounaidr** [comment]
Okay, thanks for the response.
