### ISSUE TITLE
`timeZone` option is ambiguous how it work with `format` function

### ISSUE THREAD

**Issue by turutosiya** [marnusw/date-fns-tz#21]
Hello,

Here is my test code :
https://repl.it/@turutosiya/date-fns-tz-test

```
const { format, toDate } = require('date-fns-tz');
console.log(format(toDate('2019-08-27T15:00:00Z'), 'yyyy-MM-dd', {timeZone: 'Asia/Tokyo'}));
```

What I expected to get is `2019-08-28`, Since `Asia/Tokyo` is in JST(+0900).
But in fact, I got `2019-08-27`.

Is this correct?

**Comment by marnusw** [comment]
@turutosiya I'm sorry that I never responded. Must have missed this issue.

Please see whether the updated documentation clarifies how `format` should be used and if not I would welcome any thoughts on how it can be put clearer still.
