### ISSUE TITLE
confuse

### ISSUE THREAD

**Issue by liting-yes** [marnusw/date-fns-tz#215]
why no install date-fns as dependencies when it is necessary

<img width="480" alt="Screenshot 2022-12-10 at 13 10 14" src="https://user-images.githubusercontent.com/69500429/206830478-d56c0314-7e9f-44c3-8b88-afce6f54e5a9.png">

<img width="900" alt="Screenshot 2022-12-10 at 13 11 39" src="https://user-images.githubusercontent.com/69500429/206830481-1ec57499-d444-42a3-a1c0-8f986edd7f57.png">

**Comment by marnusw** [comment]
It is a peer dependency. Choose your own version.
