### ISSUE TITLE
utcToZonedTime wrong result for Mexico since Mexico will no longer observe DST after 2022 

### ISSUE THREAD

**Issue by tclam05** [marnusw/date-fns-tz#217]
**Getting wrong results when using `utcToZonedTime` for dates after April 2, 2023, and timezone set to `America/Mexico_City`**

Up until 2023, Mexico observed DST starting on April 2. However, most of Mexico will no longer observe DST after 2023 and will continue to be in Central Standard Time. 

Reference: https://data.iana.org/time-zones/tzdb/NEWS

**Testing:**
`utcToZonedTime('2023-04-02T17:00:00.000Z', 'America/Mexico_City')`
VS
`utcToZonedTime('2023-04-01T17:00:00.000Z', 'America/Mexico_City')`

<img width="469" alt="Screenshot 2022-12-16 at 12 09 29 PM" src="https://user-images.githubusercontent.com/10451930/208161995-bdac43eb-9cd9-459c-ba26-afe261c67573.png">

**Assertion is that both will yield the same time, but the former is still adjusting for DST.**

**Comment by marnusw** [comment]
This library uses the `Intl` API of the browser or other underlying platform. It has not direct control over the DST data. You will have to wait for these platforms to update their databases.

**Comment by kingkongdog** [comment]
How to update the timezone database? Upgrade the browser?

**Comment by marnusw** [comment]
Yes, hopefully this will reflect in the browser database in the near future. You could open an issue on their bug tracker in due course if necessary.
