### ISSUE TITLE
formatInTimeZone Incorrect value z (PST/PDT)

### ISSUE THREAD

**Issue by alexeikaratai** [marnusw/date-fns-tz#228]
Incorrect zone value after formatInTimeZone when changing PST to PDT.

Dayjs works well.
We need to change PST to PDT after 2.00 AM.
But it works only if we switch the host machine to the PST time zone. 

https://codesandbox.io/s/date-fns-tz-incorect-format-yckqrg?file=/src/index.js

**Comment by patrickcate** [comment]
I can confirm I'm getting the same issue with EST/EDT.

**Comment by asennikov** [comment]
This change should fix it: https://github.com/marnusw/date-fns-tz/pull/247
