### ISSUE TITLE
Chrome 67 - 72:  Time incorrectly parsed

### ISSUE THREAD

**Issue by Semigradsky** [marnusw/date-fns-tz#230]
For Chrome 67 currently `18:00` is parsed as `6:00`.

See https://github.com/marnusw/date-fns-tz/blob/a92e0ad017d101a0c50e39a63ef5d322b4d849f6/src/_lib/tzTokenizeDate/index.js#L53-L88

We have comment here:
> New browsers use `hourCycle`, IE and Chrome <73 does not support it and uses `hour12`

But not `hourCycle` tested and in code `hour12: false` used if the hour cycle is supported. It looks like checking should be changed and `if` branches should be swapped.

**Comment by Semigradsky** [comment]
@marnusw Could you please take a look?

**Comment by Semigradsky** [comment]
UPD:
Affected browsers: at least Chrome 67 - 72

**Comment by pimothyxd** [comment]
Any updates on this?
