### ISSUE TITLE
Feature request: Compatibility with setDefaultOptions in date-fns

### ISSUE THREAD

**Issue by lnunno** [marnusw/date-fns-tz#233]
I'm not sure if this is expected to work, but I'm not seeing the options being passed into [setDefaultOptions](https://date-fns.org/v2.29.0/docs/setDefaultOptions) being respected by this library and instead have to pass in the options to each function call, for example `formatInTimeZone` needs the locale specified and doesn't use the one provided in `setDefaultOptions`

**Comment by marnusw** [comment]
You're right, it's not respected. I was either not aware of that function in date-fns or it's fairly new to be honest. Happy to support that though. I'll leave this open for when I have time or would be happy looking at a PR.

**Comment by ArianHamdi** [comment]
This is really helpful.
