### ISSUE TITLE
Timezone Offset returned instead of Timezone full name

### ISSUE THREAD

**Issue by navaneethakrishnan-gopalakrishnan** [marnusw/date-fns-tz#234]
I was searching for the timezone id "Asia/Srednekolymsk" and the result what I got in turn didn't had the appropriate timezone name, rather it returns GMT+11:00

formatInTimeZone(parisDate, 'Asia/Srednekolymsk', 'yyyy-MM-dd HH:mm:ss zzzz', { locale: enGB })

Returned Result : "2023-04-14 20:52:10 GMT+11:00"

Expected Result: "2023-04-14 20:52:10 Srednekolymsk Time"

**Comment by marnusw** [comment]
Some locales (in the browser itself) don't include names for all time zones. If you use en-US you'll see many European time zones come out as GMT+/- too. Try using a different locale. Everything comes directly from the Intl API, so there isn't much this library can do in this regard.
