### ISSUE TITLE
Missing GitHub release for the new major release

### ISSUE THREAD

**Issue by Haraldson** [marnusw/date-fns-tz#236]
Would’ve hoped this was in place by now, making it easier to get up to date on any breaking changes etc.

Edit: I see now that there’s a markdown file, but why not use the GitHub feature?

**Comment by marnusw** [comment]
GitHub creates releases based on version tags. The only way to prevent that is not using tags which isn't an option.

**Comment by Haraldson** [comment]
In my repos I manually have to create releases from tags, no automation there.

**Comment by marnusw** [comment]
I definitely don't do it manually. Perhaps there is some automation or setting configured I'm not aware of...
