### ISSUE TITLE
`OptionsWithTZ` type missing `useAdditionalDayOfYearTokens` and `useAdditionalWeekYearTokens` options

### ISSUE THREAD

**Issue by paulrobertlloyd** [marnusw/date-fns-tz#239]
The `useAdditionalDayOfYearTokens` and `useAdditionalWeekYearTokens` options are included in tests, but not included in `typings.d.ts`: https://github.com/marnusw/date-fns-tz/blob/a92e0ad017d101a0c50e39a63ef5d322b4d849f6/typings.d.ts#L30-L42

From `date-fns` [documentation on Unicode Tokens](https://date-fns.org/v2.30.0/docs/Unicode-Tokens):

> ...`format` and `parse` functions won't accept these tokens without `useAdditionalDayOfYearTokens` option for `D` and `DD` and `useAdditionalWeekYearTokens` options for `YY` and `YYYY`:
>
> ```js
> format(new Date(), 'D', { useAdditionalDayOfYearTokens: true })
> //=> '283'
>
> parse('365+1987', 'DD+YYYY', new Date(), {
>   useAdditionalDayOfYearTokens: true,
>   useAdditionalWeekYearTokens: true
> }).toString()
> //=> 'Wed Dec 31 1986 00:00:00 GMT+0200 (EET)'
> ```

**Comment by marnusw** [comment]
This should be fixed in `3.1.0` which inherits the options types from `date-fns`.

**Comment by paulrobertlloyd** [comment]
Yup, all reporting good and well now. Thanks for the fix!
