### ISSUE TITLE
[Feature Request] - Set default timezone

### ISSUE THREAD

**Issue by diegoarcega** [marnusw/date-fns-tz#24]
The idea is to implement something like:
https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

So that everytime you use any date-fns related function, you always use the same timezone.

**Comment by gund** [comment]
I think it will be better to have `zonedTimeToUtc()` argument `timeZone` optional - so if it is omitted then library will use Intl API to get current browser timezone:
```js
let clientTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone
```

**Comment by onx2** [comment]
> I think it will be better to have `zonedTimeToUtc()` and `utcToZonedTime()` argument `timeZone` optional - so if it is omitted then library will use Intl API to get current browser timezone:
> 
> ```js
> let clientTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone
> ```

This is exactly what i'm doing as a fallback, only because Typescript complains. However, it seems that it will technically work without the timezone option. Is this a Typescript only issue now?

**Comment by marnusw** [comment]
If you're going to omit the `timeZone` option and only use the system time zone then I'm not sure there is any point to use `date-fns-tz` at all. The date won't be shifted. You might as well just use `new Date(...)` directly.
