### ISSUE TITLE
Intl Android Support

### ISSUE THREAD

**Issue by eunddodi** [marnusw/date-fns-tz#249]
The issue [facebook/hermes#23](https://github.com/facebook/hermes/issues/23) has been marked as closed, indicating that Hermes now includes support for the Internationalization API (Intl). In light of this update, I would like to inquire about the current status of 'date-fns-tz' on Android in React Native. It appears that the information provided in the "Usage with Android" section of README.md may no longer be accurate or up-to-date.

Could you please confirm whether 'date-fns-tz' is now available and functional on Android in React Native with Hermes? Additionally, if there have been any changes or updates regarding its usage, it would be greatly appreciated if you could provide the latest guidance or documentation for reference.

Thank you for your assistance in clarifying this matter.

**Comment by marnusw** [comment]
@eunddodi thank you for sharing the update on Intl support in Hermes. As long as the JavaScript Intl API is supported, then `date-fns-tz` should "just work" in React Native Android apps. This library is pure JS. Any instructions for making it work on Android are purely for getting the JS Intl API working correctly. Please give it a try and if it works now we can update the README.

**Comment by Siumauricio** [comment]
Confirmed `date-fns-tz` is working with zero config in RN Version `0.72.3`

**Comment by marnusw** [comment]
Excellent @Siumauricio, thank you for investigating. I'll leave this open until I've had time to update the docs.

**Comment by marnusw** [comment]
The documentation is now up to date.
