### ISSUE TITLE
Millisecond precision

### ISSUE THREAD

**Issue by niwsa** [marnusw/date-fns-tz#25]
@marnusw While converting to a timezone the millisecond part was rounded over to 0.
Below code shows the output
```
 console.log(
                new Date(timestamp).toISOString(),
                utcToZonedTime(timestamp, timezone).toISOString()
              );
```
2019-09-30T22:01:59.117Z // actual time
2019-09-30T09:31:59.000Z // converted value.

Is millisecond precision supported by the library ?

**Comment by marnusw** [comment]
Fixed in `1.0.8` via 3a76cd8.
