### ISSUE TITLE
Buggy zonedTimeToUtc / utcToZonedTime

### ISSUE THREAD

**Issue by logineimer** [marnusw/date-fns-tz#26]
Hello there,

i discovered an issue using both `zoneTimeToUtc` and `utcToZonedTime` functions in order to convert a local (Berlin, Germany) Date to / from UTC. The following examples show that the Date won't get converted properly as the expected two hours delta is missing.

```
> new Date()
< Tue Oct 15 2019 13:49:21 GMT+0200 (Mitteleuropäische Sommerzeit)

> Intl.DateTimeFormat().resolvedOptions().timeZone
< "Germany/Berlin"
```

```
> date_fns_tz__WEBPACK_IMPORTED_MODULE_6__.zonedTimeToUtc(new Date(), 'Europe/Berlin')
< Tue Oct 15 2019 13:49:29 GMT+0200 (Mitteleuropäische Sommerzeit)
```

```
> date_fns_tz__WEBPACK_IMPORTED_MODULE_6__.utcToZonedTime(new Date(), 'Europe/Berlin')
< Tue Oct 15 2019 13:49:38 GMT+0200 (Mitteleuropäische Sommerzeit)
```

Fun fact: When using 'Etc/UTC' instead of 'Europe/Berlin' while calling the functions, it works. However, this feels liek it's not intended to be used like this.

Am I using the functions wrong or what's the problem? 😄 

Thank you in advance!

**Comment by arracos** [comment]
I'm seeing the same behavior using zonedTimeToUtc (using 'America/New York' zone).  The supplied date is being returned exactly (in local time including original time zone).

i.e. date = Tue Oct 15 2019 12:00:00 GMT-0400 (Eastern Daylight Time)
timezone = "America/New_York"
result; Tue Oct 15 2019 12:00:00 GMT-0400 (Eastern Daylight Time)

**Comment by dfoxcfive** [comment]
I am having the same problem. They were working before the last release.

**Comment by marnusw** [comment]
@dfoxcfive thanks for that note. If it was working before this is not good. I'll take a look asap.

The last release was `1.0.8`. Can you confirm whether it was working in `1.0.7` which is also recent, or only in `1.0.6` which was the previous long-standing release?

**Comment by marnusw** [comment]
Hang on @logineimer, isn't your example actually the correct behaviour?

When converting a date from `zoned` to UTC the final UTC date string should still be obtained from `date.toISOString()`. The actual date instance is and always will be in your system's local time zone. This trick this library applies is to the change the underlying UTC time to make it look like a date which is in your system local time zone is actually in another time zone.

To continue your example:

```
> const date = zonedTimeToUtc(new Date(), 'Europe/Berlin')
< Tue Oct 15 2019 13:49:29 GMT+0200 (Mitteleuropäische Sommerzeit)
> date.toISOString()
< 2019-10-15T11:49:29.000Z
```

When you log a date or use `date-fns` `format` it logs the date's local time. Therefore if you want to display the equivalent UTC of this date using `format(date, '...')` you need to zone it to your target time zone, i.e. `Etc/UTC` to print 11am:

```
> const date = zonedTimeToUtc(new Date(), 'Etc/UTC')
< Tue Oct 15 2019 11:49:29 GMT+0200 (Mitteleuropäische Sommerzeit)
> date.toISOString()
< 2019-10-15T09:49:29.000Z  // Note how the underlying UTC time will now be 9am so that the printed time becomes what you expect, because the actual date instance is still in your local time and will add +2 hours
```

You can also try setting it to British Summer Time for 12pm:

```
> const date = zonedTimeToUtc(new Date(), 'Europe/London')
< Tue Oct 15 2019 12:49:29 GMT+0200 (Mitteleuropäische Sommerzeit)
> date.toISOString()
< 2019-10-15T10:49:29.000Z  // Note how the underlying UTC time will now be 10am so that the printed time becomes what you expect, because the actual date instance is still in your local time and will add +2 hours
```

**Comment by marnusw** [comment]
Of course wherever I show `< Tue Oct 15 2019 11:49:29 GMT+0200 (Mitteleuropäische Sommerzeit)` above which is the default logged output the time zone is incorrect.

The way to get the proper time displayed would be

```js
import { format, utcToZonedTime} from 'date-fns-tz'

const timeZone = 'Europe/London'
const date = utcToZonedTime(new Date(), timeZone)
format(date, '... z', { timeZone })

< Tue Oct 15 2019 12:49:29 BST
```

**Comment by dcousens** [comment]
I too found these names / descriptions confusing,  for the benefit of others,  here is my understanding.

`zonedTimeToUtc` - changes the underlying UTC time of a date such that **5am in your local time becomes 5am in the specified timezone.**  e.g,  for 5am in Australia,  `zonedTimeToUtc(..., 'Asia/Tokyo')` would change the date to be equivalent of 5am in Tokyo.

`utcToZonedTime` - changes the underlying UTC time of a date such that **5am in your local time becomes what the local time would be in the specified timezone**.  e.g for 5am in Australia (+10), `utcToZonedTime(..., 'Asia/Tokyo')` would change the date to be equivalent of 3am in Tokyo (+8).

@marnusw maybe `zonedTimeToUtc` could be `copyLocalTimeTo(date, timeZone)`.

And then `utcToZonedTime` should be `offsetLocalTimeTo(date, timeZone)`.

**Comment by marnusw** [comment]
Thanks for sharing your thoughts @dcousens. I've also realised that the UTC/local time concepts are actually the same in practice and the correct name depends on what you are trying to achieve. When I created the library I was dealing with UTC date strings coming from an API and the names made sense. I've since actually considered exporting them as is and also under an alias with "localTime" in some form as you have suggested. I'm planning to improve the docs so I will take this into consideration, and will certainly ask for feedback here when I do.

**Comment by dcousens** [comment]
@marnusw I went with local time in my explanations above,  as that matched what `date-fns` operates on typically. (e.g `set`)

**Comment by marnusw** [comment]
Please see whether the updated documentation clarifies how `format` should be used and if not I would welcome any thoughts on how it can be put clearer still.

Changing function names and additional functionality can be considered for `date-fns-tz` v2, but for now it is important that the current functionality should be clearly understandable.

**Comment by wootwoot1234** [comment]
> I too found these names / descriptions confusing, for the benefit of others, here is my understanding.
> 
> `zonedTimeToUtc` - changes the underlying UTC time of a date such that 5am in your local time becomes 5am in the specified timezone.
> 
> * e.g,  for 5am in Australia,  `zonedTimeToUtc(..., 'Asia/Tokyo')` would change the date to be equivalent of 5am in Tokyo.
> 
> `utcToZonedTime` - changes the underlying UTC time of a date such that your local time becomes what the local time would be in the specified timezone.
> 
> * e.g, for 5am in Australia, `utcToZonedTime(..., 'Asia/Tokyo')` would change the date to have the local time of 3am.
> 
> @marnusw maybe `zonedTimeToUtc` could be `copyLocalTimeTo(date, timeZone)`.
> 
> And then `utcToZonedTime` could be `offsetLocalTimeTo(date, timeZone)`.
> 
> ```js
> const df = require('date-fns')
> const dft = require('date-fns-tz')
> 
> const threeam = new Date('2019-02-04 03:00:00') // local time
> const fiveam = df.set(threeam, { hours: 5 }) // still local
> 
> console.log(dft.copyLocalTimeTo(fiveam, 'Asia/Tokyo').toTimeString())
> // 7:00:00 am
> //   aka +2 hours, equivalent to 5am in Japan (target timezone)
> 
> console.log(dft.offsetLocalTimeTo(fiveam, 'Asia/Tokyo').toTimeString())
> // 3:00:00 am
> //   aka -2 hours, equivalent of 5am in Australia (local time)
> ```
> 
> Naming things is hard.

To further expand on this for others that come across this thread (and @marnusw please correct me if I'm wrong)

The naming is consuming to me as well but now I understand that `utcToZonedTime` is the opposite of `zonedTimeToUtc`.  So you can convert a time to and from a timezone using those two functions and you will end with the same time you started with.

All these functions are doing (again, if I understand this correctly) are adding or subtracting hours from the date object.  They figure out how many hours your local timezone is from UTC and then how many hours UTC is from the timezone you supplied and then add or subtract them.

I think it should be called: 

`zonedTimeToUtc` should be -> `fromZonedToLocal`
`utcToZonedTime` should be -> `fromLocalToZoned`

**Comment by marnusw** [comment]
Thank you @wootwoot1234 

> zonedTimeToUtc should be -> fromZonedToLocal
> utcToZonedTime should be -> fromLocalToZoned

Indeed these names seem sensible and I believe something similar has been proposed in the past as well. Initially the thinking was along these lines: You get a date from an API, probably in ISO8061format which is in UTC, along with an IANA time zone. You pass that date string and tz to `utcToZonedTime` to get the date to display. Once updated, you do the inverse and send a UTC ISO8061 date string back to the API.

> All these functions are doing (again, if I understand this correctly) are adding or subtracting hours from the date object. They figure out how many hours your local timezone is from UTC and then how many hours UTC is from the timezone you supplied and then add or subtract them.

Yes, that is essentially correct, although there is no need to figure out how far your local time is from UTC since it never enters the equation. Internally a JS date is a timestamp which represents UTC time, and the hour difference between the target time zone and UTC is added/subtracted from this. That's another reason why calling the functions "local time" may not be techincally correct (not that it needs to be at the cost of being intuitive).

I'll give the matter of a name change some though.

**Comment by wootwoot1234** [comment]
@marnusw Thank you for responding.  I truly appreciate it.  I really like your library and am very grateful that you created it and shared it.

Wow, this timezone stuff can be confusing!

So I looked at your code and although I think my statement about the two functions doing the exact opposite of each other is correct, their logic is much different.  Is there a reason for that if they seem to just do the opposite of each other?

I put together some test/example code so I could understand what the functions do.  It seems to me that it is subtracting the local timezone from the timezone passed to the function.  My browser's timezone `-5` hours from UTC and New Zealand's timezone is `+13` hours from UTC, it seems to be doing the following math `(-5) - 18 = -18` and `13 - (-5) = 18` which is taking the local timezone into account.  Maybe there is something more complicated happening in the background?

See my example below:

    const browserTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const timezone = "Pacific/Auckland";
    const date = startOfDay(new Date());
    console.log(timezone, "timezone", getTimezoneOffset(timezone, date) / (1000 * 60 * 60));
    console.log(
        browserTimezone,
        "browserTimezone",
        getTimezoneOffset(browserTimezone, date) / (1000 * 60 * 60)
    );
    console.log(date.toISOString(), "date");
    console.log(
        utcToZonedTime(date, browserTimezone).toISOString(),
        "utcToZonedTime(date, browserTimezone)",
        differenceInHours(date, utcToZonedTime(date, browserTimezone)),
        "difference"
    );
    console.log(
        zonedTimeToUtc(date, browserTimezone).toISOString(),
        "zonedTimeToUtc(date, browserTimezone)",
        differenceInHours(date, zonedTimeToUtc(date, browserTimezone)),
        "difference"
    );
    console.log(date.toISOString(), "date");
    console.log(
        utcToZonedTime(date, timezone).toISOString(),
        "utcToZonedTime(date, timezone)",
        differenceInHours(date, utcToZonedTime(date, timezone)),
        "difference"
    );
    console.log(
        zonedTimeToUtc(date, timezone).toISOString(),
        "zonedTimeToUtc(date, timezone)",
        differenceInHours(date, zonedTimeToUtc(date, timezone)),
        "difference"
    );
    console.log(
        zonedTimeToUtc(utcToZonedTime(date, timezone), timezone).toISOString(),
        "zonedTimeToUtc(utcToZonedTime(date, timezone), timezone)",
        differenceInHours(date, zonedTimeToUtc(utcToZonedTime(date, timezone), timezone)),
        "difference"
    );

Output:

    Pacific/Auckland timezone 13
    America/Chicago browserTimezone -5
    2021-03-30T05:00:00.000Z date
    2021-03-30T05:00:00.000Z utcToZonedTime(date, browserTimezone) 0 difference
    2021-03-30T05:00:00.000Z zonedTimeToUtc(date, browserTimezone) 0 difference
    2021-03-30T05:00:00.000Z date
    2021-03-30T23:00:00.000Z utcToZonedTime(date, timezone) -18 difference
    2021-03-29T11:00:00.000Z zonedTimeToUtc(date, timezone) 18 difference
    2021-03-30T05:00:00.000Z zonedTimeToUtc(utcToZonedTime(date, timezone), timezone) 0 difference
