### ISSUE TITLE
Unable to resolve path to module 'date-fns-tz'

### ISSUE THREAD

**Issue by NateYeh2023** [marnusw/date-fns-tz#268]
- date-fns  version :   3.0.6,
- date-fns-tz version： 3.0.1,

I Install date-fns-tz-v3  to solve https://github.com/marnusw/date-fns-tz/issues/260#issuecomment-1867433216

but another error just show up 

<img width="569" alt="截圖 2024-02-06 下午2 44 01" src="https://github.com/marnusw/date-fns-tz/assets/137040472/36b4e825-a8fb-4d93-bead-c2d401dcbb00">

i just can't find my date-fns-tz module

even if  I change name to 'date-fns-tz-v3'

**Comment by imaxisXD** [comment]
Same error 
./node_modules/date-fns-tz/esm/format/index.js:1:0
Module not found: Package path ./format/index.js is not exported from package /Users/abhishekmac/Desktop/Hobby Projects/aivy-post-v2/node_modules/date-fns (see exports field in /Users/abhishekmac/Desktop/Hobby Projects/aivy-post-v2/node_modules/date-fns/package.json)

**Comment by NaturesProphet** [comment]
same here
Error: Package subpath './format/index.js' is not defined by "exports" in /home/mgarcia/GitProjects/AUIM/auimPratico/node_modules/date-fns/package.json
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/mgarcia/GitProjects/AUIM/auimPratico/node_modules/date-fns-tz/format/index.js:8:37)

**Comment by mifrej** [comment]
Same here:
./node_modules/.pnpm/date-fns-tz@3.0.0-beta.0_date-fns@3.6.0/node_modules/date-fns-tz/esm/format/index.js:1:0
Module not found: Package path ./format.js is not exported from package ...

...
Import trace for requested module:
./node_modules/.pnpm/date-fns-tz@3.0.0-beta.0_date-fns@3.6.0/node_modules/date-fns-tz/esm/fp/formatWithOptions/index.js
./node_modules/.pnpm/date-fns-tz@3.0.0-beta.0_date-fns@3.6.0/node_modules/date-fns-tz/esm/fp/index.js

**Comment by public** [comment]
Same but using beta1 and date-fns 3.2.0.

**Comment by jckw** [comment]
I just contributed to the bounty on this issue:

https://until.dev/bounty/marnusw/date-fns-tz/268

The current bounty for completing it is $5.00 if it is closed within 1 month, and decreases after that.

**Comment by elirov** [comment]
I see your $5 and raise by $50.. :)

**Comment by reezpatel** [comment]
try this
in package.json
```json
"dependencies": {
    "date-fns-tz": "3.0.0-beta.2"
}
```


in your code (Assuming you are using ESM)

index.ts
```ts
import formatInTimeZone from "date-fns-tz/formatInTimeZone";
```

**Comment by marnusw** [comment]
`3.0.0-beta.3` should address all import problems. Please let me know if you encounter further issues.

**Comment by marnusw** [comment]
Please watch #273 for the official `v3.0.0` release.
