### ISSUE TITLE
How to format to specific timezone 

### ISSUE THREAD

**Issue by bagaskarala** [marnusw/date-fns-tz#27]
i still confuse how to format `2019-10-16T10:10:54+08:00` to be `16-10-2019 10:10:54` in my local time(gmt+7)

i want to be formatted as is, not converted to my local, how to do that?

note: i dont want to include `IANA Asia/Makassar` in formatting, i just want using that string only

**Comment by constgen** [comment]
Try `timeZone: 'UTC'`. In **Intl API** it gives a timezone with 0 offset. I believe it should work with this lib too.

**Comment by bagaskarala** [comment]
Where i have to give those property

**Comment by dcousens** [comment]
@bagaskarala maybe https://github.com/marnusw/date-fns-tz/issues/26#issuecomment-547767756 might be helpful to your understanding?

**Comment by bagaskarala** [comment]
> @bagaskarala maybe [#26 (comment)](https://github.com/marnusw/date-fns-tz/issues/26#issuecomment-547767756) might be helpful to your understanding?

ok but in my case, i want to format using +08:00 not string 'Asia/Makassar'

**Comment by toniton** [comment]
Great work. I am still confused as to how to use this library.

**Scenario:**

- Let's assume `552260940000` is in UTC from the server.
- I need to convert it to `America/Mecico_City` time zone
- My local time is `Europe/Berlin`

Please, can anyone guide me on how to go about this?

**Comment by marnusw** [comment]
Please see whether the updated documentation clarifies how `format` should be used and if not I would welcome any thoughts on how it can be put clearer still.

**Comment by marnusw** [comment]
@toniton 

```js
import { format, utcToZonedTime } from 'date-fns-tz'

const timestamp = 552260940000
const timeZone = 'America/Mexico_City'

const mexicoTime = utcToZonedTime(552260940000, timeZone)
format(mexicoTime, 'yyyy-MM-dd HH:mm:ss zzz', { timeZone })
```
