### ISSUE TITLE
v3 in Readme but latest on NPM still v2?

### ISSUE THREAD

**Issue by nshiab** [marnusw/date-fns-tz#275]
Hi!

First, thank you for your amazing work. :)

The readme says this at the beginning: "Time zone support for date-fns v3.0.0 using the Intl API."

But when I tried to do an npm install, it was still using date-fns v2 as a dependency, I think.

It looks like you are working on v3 and there is a beta tag on NPM.

So I guess v3 is not ready yet, right?

Maybe updating your readme would help avoid some confusion. :)

Again, thanks for the library!

**Comment by marnusw** [comment]
Good point, GitHub will be out of date at the moment. Not ideal, but not worth fixing now I think. On npm it's correct though. You can install `3.0.0-beta.3` which supports date-fns v3, even in production if you don't have a principle issue with libraries in beta.

**Comment by nshiab** [comment]
Great! Thanks!

**Comment by marnusw** [comment]
`v3.0.0` has been released.

**Comment by nshiab** [comment]
Wonderful! Thanks for all of your work! :)
