### ISSUE TITLE
Invalid time zone specified: US/Pacific

### ISSUE THREAD

**Issue by jeremybarbet** [marnusw/date-fns-tz#28]
Hi!

I'm using `react-native-localize` on my app to get user timezone. Out of it I got `US/Pacific` when then passing to my backend and handling this timezone with `date-fns-tz` I got `Invalid time zone specified: US/Pacific`.

I believe this timezone comes from a simulator device because the app is in review on the Apple store. Not sure if it's the reason and the timezone is _falsy_ for a reason.

**Comment by marnusw** [comment]
The supported time zones are fully dependent on what the `Intl` API supports. Can you see if `America/Los_Angeles` works if you hard code it? If so, you may need to map the `US/` zones to an `America/` equivalent manually on your server. Unfortunately that's not a problem this library can solve.

**Comment by jeremybarbet** [comment]
Yes, `America/Los_Angeles` works. I created a list with the timezone I found where failing: https://codesandbox.io/embed/brave-northcutt-bb5v3.

Do you know where I can find the list of the supported timezone from `Intl`?

For my issue, I will just wrap the function with a try-catch and convert to another timezone

**Comment by marnusw** [comment]
> Do you know where I can find the list of the supported timezone from Intl?

I believe the spec leaves this open ended, so it might be different per platform and in this case you'll be looking at the Node specific implementation of `Intl`. I'm not sure where that might be listed.

I'm glad you've found a solution that works. Thanks for sharing the code sandbox.

**Comment by jeremybarbet** [comment]
Just as a follow-up and to share my solution, I found on Wikipedia a list of theoretically all the deprecated timezones and the new one to use instead, and wrote a small wrapper for the `utcToZonedTime` function: https://gist.github.com/jeremybarbet/9ea9c9a013c6575d07d3645b1ae7a622
