### ISSUE TITLE
Unexpected result from format in README example

### ISSUE THREAD

**Issue by dcousens** [marnusw/date-fns-tz#29]
``` js
> const dft = require('date-fns-tz')
undefined

> const nyDate = dft.toDate('2014-10-25T13:46:20 America/New_York')
undefined

> nyDate
'2014-10-25T17:46:20.000Z' // good

> dft.format(nyDate, 'yyyy-MM-dd HH:mm:ss zzz', { timeZone: 'America/New_York' })
'2014-10-26 04:46:20 GMT-4' // bad
```
I expected `2014-10-25 13:46:20 GMT-4`.

---

Another example

``` javascript
> const parisDate = dft.toDate('2019-10-30T05:00:00 Europe/Paris')
undefined

> parisDate
'2019-10-30T04:00:00.000Z' // good

> dft.format(parisDate, 'yyyy-MM-dd HH:mm:ss zzz', { timeZone: 'Europe/Paris' })
'2019-10-30 15:00:00 GMT+1' // bad
```

I expected `2019-10-30T05:00:00 GMT+1`

---
Also,  the [examples in README](https://github.com/marnusw/date-fns-tz#format) are out of date,  they throw [`RangeError: Format string contains an unescaped latin alphabet character 'Z'`.](https://github.com/date-fns/date-fns/issues/1473) as is.

**For reference**
``` json
    "date-fns": "^2.6.0",
    "date-fns-tz": "^1.0.8",
```

**Comment by dcousens** [comment]
Another example

``` javascript
> const parisDate = dft.toDate('2014-10-25T05:00:00 Europe/Paris')
undefined

> parisDate
'2014-10-25T03:00:00.000Z'

> dft.format(parisDate, 'yyyy-MM-dd HH:mm:ss zzz', { timeZone: 'Europe/Paris' })
'2014-10-25 14:00:00 GMT+2'
```

**Comment by dcousens** [comment]
Also,  the examples in README don't work anyway.

`RangeError: Format string contains an unescaped latin alphabet character 'Z'`.

``` json
    "date-fns": "^2.6.0",
    "date-fns-tz": "^1.0.8",
```

**Comment by dcousens** [comment]
@dkozickis even your example is not working?

I tested the above on [codesandbox](https://codesandbox.io/s/quirky-microservice-i4j09)  with your versions and the below.

https://codesandbox.io/s/quirky-microservice-i4j09

The result had a different output for `zzz`, but was otherwise still wrong: `2014-10-26 04:46:20 EDT`.

**Comment by dcousens** [comment]
``` js
> format(utcToZonedTime(nyDate, 'America/New_York'), 'yyyy-MM-dd HH:mm:ss zzz', { timeZone: "America/New_York" })
'25.46.2014 13:46:20.000 GMT -04:00 (EDT)' // good

> format(utcToZonedTime(nyDate, 'America/New_York'), 'yyyy-MM-dd HH:mm:ss zzz')
'25.46.2014 13:46:20.000 GMT +11:00 (GMT+11) ' // bad
```

My understanding then is,  `format` only format's the `z`/`x`/`X`/`o`/`O`?

Am I missing something?

**Comment by marnusw** [comment]
@dcousens your last understanding that 

> format only format's the z/x/X/o/O?

is in fact correct. Times should be converted first and then formatted.

I have realised of late that this is confusing. The problem with changing the format function is that one might also want to change a date's time zone and then format it multiple times to different formats. I have, however, been considering the addition of a `formatZoneTime` function of something similar which could do both operations in one. Either way, I'm sure the docs can be clearer and will attempt to improve that first and soon.

**Comment by kroleg** [comment]
@marnusw can you please explain why timeZone affects only z/x/X/o/O? 
It makes no sense to me. When i pass timeZone to format() i expect it to display(i.e. format) time in that timezone. But instead it only replaces timezone name, so it actually outputs _another_ time (so it is not a "format").
Thanks

**Comment by marnusw** [comment]
The reason is not to change the `date-fns` format function at all, except for adding full support for z/x/X/o/O, and since this requires the IANA time zone name it has to be provided and is expected in the options. The way to use it is to use `utcToZonedTime` first and then pass the result to `format`.

I'm not sure whether this is the best way to do it or whether I'd do it like this again, but it made sense at the time. I've been contemplating adding a function such as `formatAsZonedTime` which would use the same signature but also transform the date and give the result you expect. As yet I'm undecided about doing so, though, and also what the name of such a function would be.

I hope to find time to update the docs over the holidays to make how this works clearer.

**Comment by kroleg** [comment]
If you want a separate function you can call it `formatToTimeZone` as in [date-fns-timezone](https://www.npmjs.com/package/date-fns-timezone). 

In my opinion `format` should display time in provided time zone. Internally `Date` stores timestamp (i.e. moment of time) and `Date.toString()` displays it in local/system time. If `.toString()` ever will accept `{ timeZone }` parameter if will display time in that time zone. And `format` is kind of `Date.toString()` on steroids.

**Comment by marnusw** [comment]
Please see whether the updated documentation clarifies how `format` should be used and if not I would welcome any thoughts on how it can be put clearer still.

Changing function names and additional functionality can be considered for `date-fns-tz` v2, but for now it is important that the current functionality should be clearly understandable.

**Comment by vdh** [comment]
This is really unclear in the documentation, so is `format` basically useless…?

I'm in `Australia/Brisbane` timezone, and I want to work with a date that is 8am in New York. So I make a date: "2020-01-01T13:00:00Z". But `format` doesn't want to say "8am":
```js
format(new Date("2020-01-01T13:00:00Z"), "Pp", { timeZone: "America/New_York" })
// '01/01/2020, 11:00 PM'
```

Compare to `.toLocaleString`:
```js
new Date("2020-01-01T13:00:00Z").toLocaleString("en-US", { timeZone: "America/New_York" })
// '1/1/2020, 8:00:00 AM'
```
