### ISSUE TITLE
 peerDependencies date-fns , can be updated to 4.1.0 ?

### ISSUE THREAD

**Issue by roys-qlog-co** [marnusw/date-fns-tz#300]
hi
i want to upgrade date-fns but its a  peerDependency here to version 3.0.0
any plans  to support V4 ?
thanks roy

**Comment by eshimischi** [comment]
#301

**Comment by roys-qlog-co** [comment]
@eshimischi hi see the test failed any update?
thanks for your effort

**Comment by eshimischi** [comment]
> @eshimischi hi see the test failed any update? thanks for your effort

Updated, now tests are ok. Had to level Yarn up and upgrade lock file as well

**Comment by L4Ph** [comment]
Since a timezone library has been released from date-fns, it's recommended to use that one.
Every time there's a major update to date-fns, I feel like I'm seeing this kind of back-and-forth.
https://github.com/date-fns/tz

**Comment by eshimischi** [comment]
> @roys-qlog-co
> 
> A timezone library has been released from date-fns, and it is recommended to use that instead.
> 
> While it is still immature, it's a good idea to consider switching to it in the future.
> 
> Every time there's a major update to date-fns, I feel like I'm seeing this kind of back-and-forth. https://github.com/date-fns/tz

We know it, but the thing is - this library has some extra functionality - formatters. Of course we could reimplement it within out project and new date-fns v4 and date-fns/tz but why if you have this tool already

**Comment by roys-qlog-co** [comment]
@eshimischi when you're going to release the new update?

**Comment by eshimischi** [comment]
> @eshimischi when you're going to release the new update?

i'm not an owner of this library, up to @marnusw

**Comment by eshimischi** [comment]
> hi i want to upgrade date-fns but its a peerDependency here to version 3.0.0 any plans to support V4 ? thanks roy

you can close this issue now, all done.
