### ISSUE TITLE
zonedTimeToUtc is not working for timeZone Etc/GMT+6

### ISSUE THREAD

**Issue by zitniak** [marnusw/date-fns-tz#33]
`zonedTimeToUtc('2019-11-26T10:00:00', 'America/Chicago');`   // returns correct 2019-11-26T16:00:00.000Z

`zonedTimeToUtc('2019-11-26T10:00:00', 'Etc/GMT+6');`        // returns incorrect 2019-11-26T10:00:000Z, timezone Etc/GMT+6 is silently ignored. Nor Unsupported time zone specified is thrown. It should return too 2019-11-26T16:00:00.000Z. It's Central Standard Time (CST).

Etc/GMT+6 is correct timezone identification by IANA database https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

`findTimeZone('Etc/GMT+6')` from `require('timezone-support')` confirming that timezone exists.

`zonedTimeToUtc` is not working generally with timezones 'Etc/GMT+X'.

Versions:
date-fns-tz: v.1.0.8
date-fns: v.2.8.1

**Comment by marnusw** [comment]
> findTimeZone('Etc/GMT-6') from require('timezone-support') confirming that timezone exists.

Please see if you can get this time zone to work with `Intl.DateTimeFormat` directly on the platform(s) you are targeting. If that fails then there is nothing to be done in `date-fns-tz` at the moment because it simply uses `Intl.DateTimeFormat` without any other checks.

> date-fns: v.1.30.1

This library was designed for use with `date-fns v2`. There is no guarantee it will work as expected with v1. (Although that does not seem to be the issue in this particular case.)

**Comment by zitniak** [comment]
Thanks, sorry I am using `date-fns:"2.8.1"` (I wrongly copy-pasted the version, I fixed my description).

I've tried:
```javascript
var date = new Date(Date.UTC(2019, 11, 26, 10, 0, 0));
var expectedResult = Intl.DateTimeFormat(undefined, {
    'Etc/GMT+6'
}).format(date);
```
It throws the error: `RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT+6`

Now I believe the `zonedTimeToUtc` should thrown an error too,  because the error is hidden.

BTW Moment.js handles `moment.tz('2019-11-26T10:00:00', 'Etc/GMT+6')` correctly, it returns `2019-11-26T16:00:00.000Z`

**Comment by nilamsavani** [comment]
Facing same problem. Any solution?

**Comment by NellyHayrapetyan** [comment]
> > findTimeZone('Etc/GMT-6') from require('timezone-support') confirming that timezone exists.
> 
> Please see if you can get this time zone to work with `Intl.DateTimeFormat` directly on the platform(s) you are targeting. If that fails then there is nothing to be done in `date-fns-tz` at the moment because it simply uses `Intl.DateTimeFormat` without any other checks.
> 
> > date-fns: v.1.30.1
> 
> This library was designed for use with `date-fns v2`. There is no guarantee it will work as expected with v1. (Although that does not seem to be the issue in this particular case.)

@marnusw I tried to do this `utcToZonedTime(1581509131067, 'Etc/GMT-6'))` 
It returns **Wed Feb 12 2020 12:05:31** (ignoring the given timezone),

Here is the `Intl.DateTimeFormat` implementation
```
Intl.DateTimeFormat(undefined, {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric',
      timeZone: 'Etc/GMT-6',
    }).format(1581509131067)
```
which understands the timezone and returns **2/12/2020, 6:05:31 PM**

**Comment by Pustelto** [comment]
This actually seems like problem with `tzParseTimezone` function. I have tried to check it's regexp pattern for `timezoneIANA` and it is not picking up the Etc.

![Snímek obrazovky 2021-02-04 v 13 43 17](https://user-images.githubusercontent.com/10606260/106894220-f397e600-66ee-11eb-8d05-b9dc2c5fceaa.jpg)
