### ISSUE TITLE
format to ja shows GMT+9 rather than JST

### ISSUE THREAD

**Issue by doriankoehring-bc** [marnusw/date-fns-tz#34]
```format(new Date(), PPPP p zzz, { timeZone: 'Asia/Tokyo', locale: ja })```
this should return `2019年12月4日水曜日 JST` however it returns `2019年12月4日水曜日 GMT+9`
`format` properly returns `PST` or `CST` if timeZone is `America/Los_Angeles` or `America/Chicago`.
Same thing seems to happen for timezones in europe as well. 
`Europe/Paris` returns `GMT+1` rather than `CET`
Running "date-fns": "^2.8.1" and "date-fns-tz": "^1.0.8"

**Comment by marnusw** [comment]
Please look at the second part of [the format example](https://www.npmjs.com/package/date-fns-tz#format). Unfortunately the `Intl` data for `en-US` (the default) does not produce the abbreviations for many regions outside the US. If you include a `locale` in the `options` of a zone close to the time zone you are targeting you should get better results. From `date-fns@2.6.0` the locales include the `code` and it needn't be added as shown in the example. If you don't want to include the locales in your app it will most likely also work if you pass in, as format options, `{ locale: {code: '...'} }`.

**Comment by doriankoehring-bc** [comment]
I included the locale imported from date-fns in the options in my example

**Comment by marnusw** [comment]
Could you try using `Intl.DateTimeFormat` directly with the correct locale on the platform in question and see what you get?

```js
console.log(new Intl.DateTimeFormat('ja', { timeZone: 'Asia/Tokyo', timeZoneName: 'short' }).format(new Date()));
```

When I run this in Chrome console it works fine. If it does for you, double check the `code` is available on the locale from date-fns you are using.

**Comment by doriankoehring-bc** [comment]
Hmmm. `Intl.DateTimeFormat` is showing GMT in my environment. I am running this on a node server and using `date-time-format-timezone` for the Intl polyfill. Looks like the issue is coming from there. Looks like this can be closed. Thank you!

**Comment by marnusw** [comment]
Just in case this is your issue, if you're running on Node be sure to include full ICU data: https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime
