### ISSUE TITLE
IE11 not accepting timezones

### ISSUE THREAD

**Issue by Ztokke** [marnusw/date-fns-tz#37]
When I enter Europe/Berlin as timezone all browsers accepts this but of course Internet Explorer does not. I get the following error code:

_Error in render: "RangeError: Option value 'EUROPE/BERLIN' for 'timeZone' is outside of valid range. Expected: ['UTC']"_

**Comment by marnusw** [comment]
You probably need a polyfill for Intl on IE.

**Comment by marnusw** [comment]
Also make sure you include all the specific locale polyfills. i.e. for each language there is usually additional data to add, like `en.json`, `de.json` etc. You can refer to the polyfill library documentation for details.
