### ISSUE TITLE
utcToZonedTime not working?

### ISSUE THREAD

**Issue by mateusgrb** [marnusw/date-fns-tz#49]
Using the [example on line 26 of utcToZonedTime/index.js](https://github.com/marnusw/date-fns-tz/blob/b8e458e7b7dd7fec17c46b7c0d6125312548a44c/src/utcToZonedTime/index.js#L26), I did this:

`const result = utcToZonedTime('2014-06-25T10:00:00.000Z', 'America/New_York').toISOString()`;

I expected `result` to equal `2014-06-25T06:00:00.000Z`, but it's actually `2014-06-25T09:00:00.000Z`. Why does that happen? Is it considering the first param to be in the local timezone rather than UTC? cause I'm in GMT-3 and NY is just 1 hour away(in June), hence my suspicion.

I'm on node 8.9.4, date-fns-tz 1.0.10.

**Comment by hstom** [comment]
Since your string has a Z suffix it is being considered as UTC, even though you're passing a timezone

**Comment by marnusw** [comment]
You can use `parseJSON` from `date-fns` to convert the ISO date string to a `Date` first.

**Comment by SarantopoulosKon** [comment]
@mateusgrb did you get it to work? It seems i have a similar problem. I want to convert a utc date string `2014-06-25T10:00:00.000Z` to Tokyo (`GMT+9`) so instead of getting 19:00 time i get 16:00 and i believe these 3 hours less have to do with my current timezone which is `GMT+3`.

**Comment by cardiweb** [comment]
> @mateusgrb did you get it to work? It seems i have a similar problem. I want to convert a utc date string `2014-06-25T10:00:00.000Z` to Tokyo (`GMT+9`) so instead of getting 19:00 time i get 16:00 and i believe these 3 hours less have to do with my current timezone which is `GMT+3`.

I suppose that the output got an offset. If you log at getTimezoneOffset() on the output it should be -180.

To be clean, I suppose that the output here : 
https://github.com/marnusw/date-fns-tz/blob/master/src/utcToZonedTime/index.js#L35
should have a 0 offset.

**Comment by ElvenMonky** [comment]
> Since your string has a Z suffix it is being considered as UTC, even though you're passing a timezone

Is not the purpose of `utcToZonedTime` to convert UTC time into the time in specific timezone?
First argument should be considered UTC, local time should not be involved at all. Can someone elaborate on how current behavior can be correct?

**Comment by kimamula** [comment]
> You can use `parseJSON` from `date-fns` to convert the ISO date string to a `Date` first.

This does not help:

```js
> utcToZonedTime(parseJSON('2014-06-25T10:00:00.000Z'), 'America/New_York').toISOString() === utcToZonedTime('2014-06-25T10:00:00.000Z', 'America/New_York').toISOString()
true
```

The combination of `utcToZonedTime` and `zonedTimeToUtc` gives me the expected output:

```js
> utcToZonedTime(zonedTimeToUtc('2014-06-25T10:00:00.000Z', 'UTC'), 'America/New_York')
2014-06-25T06:00:00.000Z
```

**Comment by IgnacioYanjari** [comment]
@ElvenMonky  here is the explanation on how it works https://github.com/marnusw/date-fns-tz/issues/26#issuecomment-543081274
