### ISSUE TITLE
 'Etc/GMT-6' timezone id and other Etc/GMT zones are not working with utcToZonedTime

### ISSUE THREAD

**Issue by NellyHayrapetyan** [marnusw/date-fns-tz#50]
I tried to do this utcToZonedTime(1581509131067, 'Etc/GMT-6'))
It returns Wed Feb 12 2020 12:05:31 (ignoring the given timezone),

Here is the Intl.DateTimeFormat implementation

Intl.DateTimeFormat(undefined, {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric',
      timeZone: 'Etc/GMT-6',
    }).format(1581509131067)
which understands the timezone and returns 2/12/2020, 6:05:31 PM

**Comment by zanctor** [comment]
Any updates on this issue?

**Comment by zanctor** [comment]
@marnusw, I checked it again and seems like it works fine with the current lib version. I believe the original issue was related to that time period when the lib was not working properly with all the IANA timezones.

**Comment by marnusw** [comment]
Thank you @zanctor
