### ISSUE TITLE
The utcToZonedTime function adds an extra day if the timeZone parameter is "UTC" and the date is between "00:00:00.000Z" and "00:59:59.999Z"

### ISSUE THREAD

**Issue by adc-mhaugen** [marnusw/date-fns-tz#53]
The `utcToZonedTime` function adds an extra day if the `timeZone` parameter is "UTC" and the time portion of the passed date value is between "00:00:00.000Z" and "00:59:59.999Z".

```
window.console.log(utcToZonedTime(new Date('2020-02-19T18:59:59.999-0500'), 'UTC')); // Wed Feb 19 2020 23:59:59 GMT-0500 (Eastern Standard Time)
window.console.log(utcToZonedTime(new Date('2020-02-19T19:00:00.000-0500'), 'UTC')); // Fri Feb 21 2020 00:00:00 GMT-0500 (Eastern Standard Time)
window.console.log(utcToZonedTime(new Date('2020-02-19T19:59:59.999-0500'), 'UTC')); // Fri Feb 21 2020 00:59:59 GMT-0500 (Eastern Standard Time)
window.console.log(utcToZonedTime(new Date('2020-02-19T20:00:00.000-0500'), 'UTC')); // Thu Feb 20 2020 01:00:00 GMT-0500 (Eastern Standard Time)
```

Using date-fns-tz@1.0.9.

**Comment by adc-mhaugen** [comment]
Looks like this issue may only happen in Chrome 80.

**Comment by eugene-platov** [comment]
Had the same issue in chrome 80. Firefox and safari worked fine
Updating to version 1.0.10 solved this
This comment helped https://github.com/marnusw/date-fns-tz/issues/38#issuecomment-584057613

**Comment by shivkumarganesh** [comment]
We are experiencing the same issue. Is there a fix provided for the same.

**Comment by marnusw** [comment]
I've tested this with `v1.2.2` and the latest Chrome and it seems to work fine now.
