### ISSUE TITLE
Timezone abbreviation doesn't seem to always work?

### ISSUE THREAD

**Issue by fc** [marnusw/date-fns-tz#54]
Using the latest version of date-fns:

```
format(zonedDate, 'yyyy-MM-dd HH:mm:ss zzz', { timeZone: 'Europe/Paris' })
// Expected output: 2014-10-25 06:46:20 CET
// Actual output: 2020-02-21 23:45:00 GMT+1
```

Yet when I used `America/New_York` it was correct.

I was able to get something working with `timezone-support` to get the timezone abbreviation value I wanted for now though.

**Comment by spacedawwwg** [comment]
I'm having the same issue

**Comment by kuzvac** [comment]
@marnusw sorry to bothering you, but maybe some advice to how fix this, or something? :(

**Comment by marnusw** [comment]
Unfortunately the output is determined by the `Intl` implementation of Node / the browser and gives different output for different locales. Specifying a locale from the same continent as the time zone seems to be the best bet for getting the desired output in all cases.
