### ISSUE TITLE
utcToZonedTime android Intl: timeZone is not supported

### ISSUE THREAD

**Issue by s-aleinik** [marnusw/date-fns-tz#59]
Thank you for the amazing library! But there is one thing. I came here from react-native. It works perfectly for iOS but with android there's an issue I ran to:

```
import { utcToZonedTime, format } from 'date-fns-tz';

const TIME_ZONE = 'Europe/Berlin';

export const formatDate = (
  date: Date | number,
  currentFormat: string
): string => {
  const utcTime = new Date(date);
  const zonedTime = utcToZonedTime(utcTime, TIME_ZONE);

  return format(zonedTime, currentFormat, { timeZone: TIME_ZONE });
};
```
currentFormat there is simple: `'dd.MM.y H:mm'`

The problem is that using `utcToZonedTime` throws an error: `RangeError: timeZone is not supported.`

I think it connected with Intl. Have anyone already faced it and, probably, found a solution?

**Comment by s-aleinik** [comment]
Found a solution: 
1) `def jscFlavor = 'org.webkit:android-jsc:+'` should be replaced with `def jscFlavor = 'org.webkit:android-jsc-intl:+'` in `app/build.gradle`. 
2) `intl` should be installed - `yarn add intl`
3) Locales should be imported where needed:

```
import 'intl';
import 'intl/locale-data/jsonp/en';
import 'intl/locale-data/jsonp/de';
```

**Comment by pdpino** [comment]
I had the same problem. Using only the first step was enough to fix it.
Thanks!

**Comment by mrnmilutinovic** [comment]
This should probably end up in a readme :) 
Thanks @s-aleinik
