### ISSUE TITLE
utcToZonedTime adds one day

### ISSUE THREAD

**Issue by fhavrlent** [marnusw/date-fns-tz#61]
Hello,

I have an issue with the lib, not sure if I am using it wrong or it's a bug.

Right now, it's 16:30 in CET. I changed my time zone to Sydney, so `new Date()` will return `Fri Mar 27 2020 02:36:03 GMT+1100 (Australia Sydney Standard Time)`.  I would expect the code snipped down bellow to generate `2020-03-26`, instead I am getting `2020-03-28`. Am I doing something wrong? 

```
const timeZone = "America/Chicago";
const inUTC = zonedTimeToUtc(new Date(), "Australia/Sydney");
const utcToZOned =  utcToZonedTime(inUTC, timeZone);

const formated = format(utcToZOned, "yyyy-MM-dd", {timeZone});
console.log(formated)

```

**Comment by dcousens** [comment]
Why close @fhavrlent

**Comment by fhavrlent** [comment]
@dcousens Found out it was issue with the browser plugin I was using to change time zone. After changing it in OS settings, it works as expected.

**Comment by dcousens** [comment]
Thanks for the followup.
