### ISSUE TITLE
Date incorrect date when using format with timeZone

### ISSUE THREAD

**Issue by victornpb** [marnusw/date-fns-tz#63]
1. Computer time set to `2020-03-**03** 11:00 PM GMT-7` (California)
2. At this exact moment GMT-03 should be the next day 2020-03-**04**

![image](https://user-images.githubusercontent.com/3372598/78393731-410f6800-759f-11ea-8312-eabb527ea120.png)

```js
const { toDate, format } = require('date-fns-tz');

console.log('              UTC:', new Date().toUTCString());
console.log('       Local time:', new Date().toTimeString());
console.log('America/Sao_Paulo:', format(new Date(), 'yyyy-MM-dd HH:mm:ss  zzz', { timeZone: 'America/Sao_Paulo' }));
```
Output:
```
$ date
Fri Apr  3 23:37:51 PDT 2020
$ node --version
v10.15.1
$ node .
              UTC: Sat, 04 Apr 2020 06:37:59 GMT
       Local time: 23:37:59 GMT-0700 (Pacific Daylight Time)
America/Sao_Paulo: 2020-04-03 23:37:59  GMT-3
```

```json
  "dependencies": {
    "date-fns": "^2.11.1",
    "date-fns-tz": "^1.0.10"
  }
```

**Comment by ankit-gaur** [comment]
this suggests to convert to zoned time before formatting https://date-fns.org/v2.21.1/docs/Time-Zones

**Comment by marnusw** [comment]
```js
formatInTimeZone(new Date(), 'America/Sao_Paulo', 'yyyy-MM-dd HH:mm:ss  zzz')
```

will give the result you were after.

**Comment by victornpb** [comment]
Do you think this could be in the docs? I could submit a pr if point me to the right resource

**Comment by marnusw** [comment]
Just see whether you don't find the docs clearer already now. `formatInTimeZone` is a new function which wraps what had to be done separately with `utcToZonedTime` and `format` in a single step. If you think there is a way to improve the docs further still I'd welcome a PR, thanks.
