### ISSUE TITLE
Do you provide stripped TZ database?

### ISSUE THREAD

**Issue by gavenkoa** [marnusw/date-fns-tz#66]
https://github.com/prantlf/timezone-support says:

> Smaller bundles of code with limited data - 1900-2050 (206 kB minified, 25.4 kB gzipped), 1970-2038 (141 kB minified, 15.8 kB gzipped) and 2012-2022 (31.3 KB minified, 8.25 kB gzipped).

How can `date-fns-tz` be configured to use smaller TZ database (with reduced history)?

https://momentjs.com/timezone/ also provides alternative stripped databases.

In most applications we don't need wired TZ data during Mexican revolution in 1910's, when each city had own day saving pattern.  Actually we don't need anything odler than 2012.

**Comment by marnusw** [comment]
This library does not bundle a tz database at all. It uses the browser Intl API which should make it as light weight a lib for time zone handling as possible.
