### ISSUE TITLE
How can you run startOfDay in your timezone?

### ISSUE THREAD

**Issue by thomaschaaf** [marnusw/date-fns-tz#67]
How can I run startOfDay and pass a timezone?

**Comment by mediafreakch** [comment]
I have the same question but for `endOfMonth` and `startOfMonth`. 

My use-case is the following: 

There is a DB containing events in a given timeZone, stored as ISO Strings (UTC). So, an event that occured at `May 31st at 11pm PDT` will be stored as `2020-06-01T06:00:00Z`. 

In a web app I let the user select the month he wants to see events for (zero based, 0-11). The user is not necessarily in the timeZone of the event though, but wants to see only events that fall in the time range of the month in the recorded timezone. 

So for May as the selected month (4), I would need to send the following timestamps to the server: 

```
GET /events?from=2020-05-01T07:00:00Z&to=2020-06-01T07:00:00Z`
```

I don't see how to accomplish this as `endOfMonth` in `date-fns` returns a date in local time....

**Comment by mediafreakch** [comment]
Looks like this is what I need for my use-case ([seen here](https://github.com/date-fns/date-fns/issues/669#issuecomment-455087997)):

```
export function getFirstOfMonthInStationTime(month: number, timeZone: string): Date {
  const utcDate = new Date(Date.UTC(new Date().getFullYear(), month, 2, 0, 0))
  const timeZoneDate = utcToZonedTime(utcDate, timeZone)
  const timeZoneStartOfMonth = startOfMonth(timeZoneDate)
  const startOfMonthForDB = zonedTimeToUtc(timeZoneStartOfMonth, timeZone)

  return startOfMonthForDB
}

export function getLastOfMonthInStationTime(month: number, timeZone: string): Date {
  const utcDate = new Date(Date.UTC(new Date().getFullYear(), month, 2, 0, 0))
  const timeZoneDate = utcToZonedTime(utcDate, timeZone)
  const timeZoneEndOfMonth = endOfMonth(timeZoneDate)
  const endOfMonthForDB = zonedTimeToUtc(timeZoneEndOfMonth, timeZone)

  return endOfMonthForDB
}
```

I expect this to work similar for `startOfDay`. However I don't quite understand why this fails with the day set to `0` or `1`, but works with day set to `2` like in the example.

**Comment by NiklasPor** [comment]
Hey, @mediafreakch is already right here. I'll just add a more explicit example with `startOfDay`.

In this case, we want to know the start of the day `2021-09-27T03:00:16.000Z`(UTC) in New York time. So at which point of time the day in `America/New_York` starts. My browser is running in `Germany/Berlin` time.

> The first `utcToZonedTime` is important, because otherwise you might not get the correct day. In this case the day in Germany would be already the **27th**, but in New York the day is still the **26th**.

```ts
// UTC: 09-27 03:00
// Browser (Germany/Berlin): 09-27 05:00
// Target (America/New_York): 09-26 23:00
const input = parseISO('2021-09-27T03:00:16.000Z');

// UTC: 09-27 21:00
// Browser (Germany/Berlin): 09-26 23:00
const inputZoned = utcToZonedTime(input, 'America/New_York');

// UTC: 09-25 22:00
// Browser (Germany/Berlin): 09-26 00:00
const dayStartZoned = startOfDay(inputZoned);

// UTC: 09-26 04:00
// Browser (Germany/Berlin): 09-26 06:00
// Target (America/New_York): 09-26 00:00
const dayStart = zonedTimeToUtc(dayStartZoned, 'America/New_York');
```

**Comment by KirillKotliar** [comment]
Examples above seem not working. Functions like `startOfDay` always return date based on the current timezone. Here is another way. In my case I needed to get start and end dates of the current month in another timezone. 
```
import {endOfMonth, startOfMonth} from 'date-fns';
import {getTimezoneOffset} from 'date-fns-tz';

const transformDateToTimezone = (date: Date, timeZone: string) => {
  const targetTimezoneOffset = getTimezoneOffset(timeZone);
  return new Date(date.getTime() - date.getTimezoneOffset() + targetTimezoneOffset);
};

const now = new Date();
const targetTimezone= 'America/Los_Angeles';

const startDateLocal = startOfMonth(now);
const endDateLocal = endOfMonth(now);

const startDateZoned = transformDateToTimezone(fromDateLocal, targetTimezone);
const endDateZoned = transformDateToTimezone(toDateLocal, targetTimezone);
```

So the idea is to find dates in a current timezone first then shift it to the target one.

**Comment by hanayashiki** [comment]
Use `@date-fns/tz` instead which handles this sanely.

I'm at `Asia/Tokyo` and run

```ts
console.log(startOfDay(new TZDate(2023, 0, 1, "America/Los_Angeles")).toISOString());

2022-12-31T00:00:00.000-08:00
```
 But, i would not recommend handling timezone related problems with date-fns or date-fns-tz or @date-fns/tz at all. 

All of them do not handle the lack of timezone support in the original date in a sensible way. I know they are using tricks like Intl to get offset, or offset the Date object to tweak hour and minutes, but none of them are explicitly stated and explained, leaving the user wonder "how start of day works". From the view of subtype and supertype, you just cannot pass TZDate to a function accepting Date to expect valid results.
