### ISSUE TITLE
Offset not considering PDT

### ISSUE THREAD

**Issue by shivkumarganesh** [marnusw/date-fns-tz#70]
The offset is not considering for pacific timezone. Right now we are in PDT but the timezone always formats the time according to PST. Rather than using GMT-07:00 rather I always end up getting GMT-08:00. The example is mentioned below

```
require("date-fns/package.json"); // date-fns is a peer dependency. 
var dateFnsTz = require("date-fns-tz")

const laTimeZone = 'America/Los_Angeles'
const laDate = dateFnsTz.utcToZonedTime(new Date('2020-02-02T06:59:00z'), laTimeZone);
console.log(laDate)

// WRONG RESULT - Sat Feb 01 2020 22:59:00 GMT-0800 (Pacific Standard Time)

// CORRECT RESULT - Sat Feb 01 2020 23:59:00 GMT-0700 (Pacific Standard Time)
```
Is there any way to accommodate the DST along with the timezone

**Comment by SirLamer** [comment]
February dates per your example are in Standard Time, that's why.

Try a summer date.

**Comment by marnusw** [comment]
Thank you @SirLamer.
