### ISSUE TITLE
Is it possible to format date from UTC to local time zone (EST for example) on ie11?

### ISSUE THREAD

**Issue by LordOfCorners** [marnusw/date-fns-tz#71]
Is it possible to format date from UTC to local time zone (EST for example) on ie11? On ie11 I'm getting a `'` where the time zone would be using `z` in the format string. I have tried using the Intl polyfill as well as the date-time-format-timezone polyfill.

If it's not possible I'll just leave it off.

**Comment by pcash007** [comment]
Same problem here. Did you find a solution? thank you.

**Comment by marnusw** [comment]
You need a polyfill for the browser Intl API. I think there is a link in the readme.
