### ISSUE TITLE
bug: utcToZonedTime and format (with timezone param) dont work correctly

### ISSUE THREAD

**Issue by destradafilm** [marnusw/date-fns-tz#72]
As you can see from my example. The timestamp has the "z" suffix specifying that it's UTC. When I try to convert UTC to local time, only local time is returned

```
  const tstamp = '2020-05-11T05:27:07.292Z'

  const date = new Date(tstamp)
  const localTimeZone = "America/Denver"
  const zonedTime = utcToZonedTime(date, localTimeZone)
  const datefnsFormatted = format(zonedTime, "yyyy-MM-dd", {
            timeZone: localTimeZone
          })
```
works fine with `momentjs`

see codepen example:
https://codepen.io/destrada/pen/OJMVPNV

**Comment by cben** [comment]
Not a bug.  When it's 5am over Greenwich :earth_africa:, it's still previous night over Denver :earth_americas:.

To debug something like this, you should print the hours and minutes, and also include the time zone in the format.
See https://codepen.io/cben/pen/XWdrKQX:
date-fns-tz UTC to local time: 2020-05-10 23:27 -06:00 :heavy_check_mark:
momentJS UTC .utc.format: 2020-05-11 05:27 +00:00 :exclamation: 
momentJS UTC .tz.format: 2020-05-10 23:27 -06:00 :heavy_check_mark: 
(I run this in Chrome 84, Linux, under Asia/Jerusalem system tz)

What confused you is how you called MomentJS. `moment.utc()` sets object's timezone to be UTC, so you were formatting the input date back into UTC, and naturally got the original May 11!    I also had to add [moment-timezone-with-data.min.js](https://momentjs.com/timezone) library for calling the correct `moment(date).tz(localTimeZone).format(...)`.

**Comment by marnusw** [comment]
Thank you @cben.
