### ISSUE TITLE
Unit testing mock date

### ISSUE THREAD

**Issue by andyghiuta** [marnusw/date-fns-tz#73]
Trying to add some unit tests to functions that convert from local timezone to a particular timezone, and for being able to run the tests on different timezones, I'm trying to mock the TZ to UTC (local time is EST).

What's a good way to do that?

Example (mocha):
```javascript
import { expect } from 'chai';
import tk from 'timekeeper';
import timezoneMock from 'timezone-mock';
import { utcToZonedTime } from 'date-fns-tz';

const LOCAL_TZ = 'UTC';
const TARGET_TZ = 'America/Chicago'; // -06:00

describe('test class', () => {

  beforeEach(() => {
    timezoneMock.register(LOCAL_TZ );
    tk.freeze(new Date('2020-01-01T06:00:00.000Z'));
  });

  afterEach(() => {
    tk.reset();
    timezoneMock.unregister();
  });

  it('calculates dates with timezone', () => {
    expect(utcToZonedTime(new Date(), TARGET_TZ).toISOString()).to.eq('2020-01-01T00:00:00.000Z');
  });
})
```

**Comment by marnusw** [comment]
I think to run tests across mutliple time zones the best bet is to use CI to create environments with different system time zones and run your tests in each of them. See https://github.com/marnusw/date-fns-tz/blob/master/.circleci/config.yml.
