### ISSUE TITLE
Time zones list

### ISSUE THREAD

**Issue by ktrzos** [marnusw/date-fns-tz#74]
Is there any way of getting timezones list from `date-fns-tz`?

**Comment by toddheslin** [comment]
According to the first line of the readme:
`Time zone support for date-fns v2.0.0 using the Intl API. By using the browser API no time zone data needs to be included in code bundles. Modern browsers all support the necessary features, and for those that don't a polyfill can be used.`

I've just started using the package but I believe it relies on the browser's own list of timezones based on Intl.

Based on the [ECMAScript spec](https://tc39.es/ecma402/#sec-time-zone-names) browsers should implement the IANA Time Zone Database.
