### ISSUE TITLE
Help displaying date/times using server's timezone only

### ISSUE THREAD

**Issue by ktsangop** [marnusw/date-fns-tz#78]
I would like some help regarding the usage of `date-fns-tz`, and could not find any related info, either on the documentation, or anywhere online.

We need to practically show only server date/times on our client application.
This means that the client app should always behave like it runs on the same timezone as the server.

Previously using `moment-timezone` we could explicitly "alter" the timezone of the client using the tz name rerpresentation e.g. "America/New_York".
`moment.tz.setDefault("America/New_York");`

Our servers return date/times in ISO format like : 
`2020-07-29T23:30:00.000-0400`

Is there any way using this library to simplify parsing and displaying of those dates on the client without being affected of client machine timezones?

Thank you in advance.

**Comment by marnusw** [comment]
You will need to use `utcToZonedTime` on each date received by the client and pass your preferred time zone, i.e. the your server's time zone, as the second argument. You can create a helper function for formatting your dates, something like:

```js
import { utcToZonedTime, format } from 'date-fns-tz'

const serverTimeZone = '...'

export const formatServerDate = (date, pattern) => 
  format(utcToZonedTime(date, serverTimeZone), pattern, { timeZone: serverTimeZone })
```

**Comment by ktsangop** [comment]
Thank you for your answer. The docs state that :
_..Say the server provided a UTC date/time and a time zone..._
https://www.npmjs.com/package/date-fns-tz#utctozonedtime

From what I understand `utcToZonedTime` requires a UTC date/time, and as I had previously stated: 
```
Our servers return date/times in ISO format like :
2020-07-29T23:30:00.000-0400
```
