### ISSUE TITLE
utcToZonedTime() incorrect for Pacific/Honolulu

### ISSUE THREAD

**Issue by doriankoehring-bc** [marnusw/date-fns-tz#81]
```
    const utcDate = new Date('2020-09-24T09:59:59.000Z');
    console.log(1, utcDate);
    const testDate = utcToZonedTime(utcDate, 'Pacific/Honolulu');
    console.log(2, testDate);
```
Output:
```
1 2020-09-24T09:59:59.000Z
2 2020-09-24T06:59:59.000Z
```
This should return `2020-09-23T23:59:59.000Z`.
Works as expected for all other timezones.

Running on node 14.8 locally, not on the browser.

**Comment by doriankoehring-bc** [comment]
interestingly enough applying `format` to it seems to output the correct date.
`const formatted = format(testDate, 'Ppp z', { timeZone: 'Pacific/Honolulu', locale: enUS })`
`09/23/2020, 11:59:59 PM HST`

**Comment by shaungrady** [comment]
https://stackblitz.com/edit/typescript-rqfxfg?file=index.ts

When logging the dates, call the `.toString()` method. Your mistake is that you're expecting the Zulu (UTC) time shown in your second `console.log` to represent the local Hawaiian time. It does not. It represents the local Hawaiian time as it would be in Greenwich.

**Comment by shaungrady** [comment]
https://stackblitz.com/edit/typescript-rqfxfg?file=index.ts

```ts
const utcDate = new Date("2020-09-24T09:59:59.000Z");
console.log(1, utcDate.toString());
const testDate = utcToZonedTime(utcDate, "Pacific/Honolulu");
console.log(2, testDate.toString());
```
```
1 Thu Sep 24 2020 02:59:59 GMT-0700 (Pacific Daylight Time)
2 Wed Sep 23 2020 23:59:59 GMT-0700 (Pacific Daylight Time)
```


When logging the dates, call the `.toString()` method. Your mistake is that you're expecting the Zulu (UTC) time shown in your second `console.log` to represent the local Hawaiian time. It does not. It represents the local Hawaiian time as it is exists in Greenwich.

**Comment by marnusw** [comment]
Looks like this has been resolved. Thank you @shaungrady.
