### ISSUE TITLE
utcToZonedTime() incorrect for EST

### ISSUE THREAD

**Issue by rabhilashbanapuram** [marnusw/date-fns-tz#83]
I have date and time saved in UTC, which I should convert to user timezone and display.

The utcToZonedTime() returns the correct value when I pass "America/New_York" and "Asia/Kolkata", but when I pass "EST", the returned value remains the same.

The expected result should be 5 hours behind UTC.

I have created a demo here:
https://stackblitz.com/edit/angular-ivy-qn4mhm?file=src%2Fapp%2Fapp.component.ts

Code:
```
    const utcdate = new Date("2018-09-01Z18:00:00.000Z");
    this.estDateTime = format(
      utcToZonedTime(utcdate, "EST"),
      "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    );
```
Current result:2018-09-01Z18:00:00.000Z

Expected result:2018-09-01T13:00:00.000Z

Can somebody please tell me where I am doing wrong

**Comment by marnusw** [comment]
@rabhilashbanapuram think the problem is that the native Intl API does not support parsing time zone name abbreviations, it only supports IANA time zone names and numeric time zone offsets. Since this library specifically opts to only use the built in Intl API this cannot be supported.
