### ISSUE TITLE
Years below 100 not allowed?

### ISSUE THREAD

**Issue by donaldpipowitch** [marnusw/date-fns-tz#87]
Hi! Not sure if this is a bug or "intended"/due to some date quirks, but I can't use a year below 100.

```
zonedTimeToUtc('0100-01-01', 'Europe/Berlin').toISOString()
// === "0099-12-31T23:06:32.000Z"

zonedTimeToUtc('0099-01-01', 'Europe/Berlin').toISOString()
// === "-001801-01-01T23:06:32.000Z"
```

**Comment by marnusw** [comment]
Certainly not intentional. I can't guarantee that I'll be able to look at this any time soon since it seems like quite an edge case. I'd welcome a PR though. You can also check the date-fns library directly to see if they support it, because the `toDate` function was copied from date-fns some versions ago.

**Comment by donaldpipowitch** [comment]
Thanks for the quick reply.

**Comment by make-github-pseudonymous-again** [comment]
[This bug probably stems from the `Date` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#interpretation_of_two-digit_years).

**Comment by make-github-pseudonymous-again** [comment]
Note that [there used to be a similar bug in `date-fns`](https://github.com/date-fns/date-fns/issues/257) but it has been fixed a long time ago (November 2016).

**Comment by make-github-pseudonymous-again** [comment]
I get the following output on runkit (`date-fns`v2.28.0, `date-fns-tz`v1.3.0):

```js
zonedTimeToUtc('0099-01-01', 'Europe/Berlin').toISOString()
"1998-12-31T23:00:00.000Z"
```

**Comment by make-github-pseudonymous-again** [comment]
Just wrote a draft PR #170 fixing this issue.

**Comment by marnusw** [comment]
Thanks, will take a look as soon as I can.
