### ISSUE TITLE
Wrong time zone offset near DST boundaries

### ISSUE THREAD

**Issue by bsvetlik** [marnusw/date-fns-tz#93]
Take a look on the following example: 1 hour is lost in conversions.
Local time zone: GMT+0000 (Greenwich Mean Time)
Good hours: before 2:00 and after 7:00
Bad hours: between 2:00 and 7:00

import { zonedTimeToUtc, utcToZonedTime, format } from "date-fns-tz";

var nyTime = "2020-03-08 02:00:00"; // begin of the summer time: 2020-03-08T07:00:00.000Z
console.log("### nyTime = ", nyTime); // 2020-03-08 02:00:00 - local time in NY

var utcDate = zonedTimeToUtc(nyTime, "America/New_York");
console.log("### utcDate.toISOString() = ", utcDate.toISOString()); // lost 1 hour!: 2020-03-08T06:00:00.000Z

var d2 = utcToZonedTime(utcDate, "America/New_York");
var nyTime2 = format(d2, "yyyy-MM-dd HH:mm:ssX", {
  timeZone: "America/New_York"
});

// only after 7:00 offset changes to the summer time (local time zone is UTC)
console.log("### nyTime2 = ", nyTime2); // oops!: 2020-03-08 01:00:00-05

see https://codesandbox.io/s/heuristic-shtern-swg95?file=/src/index.js

Note #1: The local time zone was deliberately set to UTC in the Windows 10 Date & Time settings in order to eliminate the effect of the particular time zone.
Note #2: These transitions work fine in the luxon library, so the DST problem can be easily fixed by applying corresponding code from the luxon library.

**Comment by marnusw** [comment]
Thank you for reporting this issue. Please see if `v1.0.10` before the recent changes has the same problem.

If you would please submit a PR with failing unit tests that will be most helpful.

Also, re Note #2, if you have time to do this in a PR that will be most appreciated.

**Comment by marnusw** [comment]
Actually, since your issue is DST related it probably will be present in v1.0.10. The Luxon implementation should be the answer...

**Comment by bsvetlik** [comment]
Fixed this issue on the master branch. I think that this change will fix also a lot of other Time Zone related issues.

**Comment by yharaskrik** [comment]
https://github.com/marnusw/date-fns-tz/pull/108

**Comment by marnusw** [comment]
Closed in #108. See v1.1.2
