### ISSUE TITLE
utcToZonedTime returns incorrect results for numerous timezones

### ISSUE THREAD

**Issue by DiagoSmith** [marnusw/date-fns-tz#94]
Hi,
first of all, 
I love the library so thanks for the time spent in making it!

I've been encountering an issue when using the `utcToZonedTime` function with certain timezones. 

Here's one example:

```
const mountainDate = new Date();
const mountainTest = utcToZonedTime(
  setHours(
    new Date(
      Date.UTC(
        mountainDate.getUTCFullYear(),
        mountainDate.getUTCMonth(),
        mountainDate.getUTCDate(),
        mountainDate.getUTCHours()
      )
    ),
    8,
  ),
  "MST"
);

console.log({ mountainTest });
```

I would expect this to return UTC -7 but it instead just returns the same UTC time. I tried it using the Intl.DateTimeFormat api and it works as expected there: 

```
console.log(new Intl.DateTimeFormat('en-GB',{timeZone: 'MST', dateStyle: 'full', timeStyle: 'full'}).format(date))
```
Some other timezones that have similar issues that I've noticed so far:

```
   "/US/Indiana-Starke",
  "US/East-Indiana",
  "Navajo",
  "US/Pacific-New"
```

**Comment by marnusw** [comment]
Thank you for reporting this issue. Please see if `v1.0.10` before the recent changes has the same problem.

If you would please submit a PR with failing unit tests that will be most helpful.

**Comment by tremby** [comment]
I'm on v1.0.12 and `utcToZonedTime` isn't doing at all what I expect.

```
[bjn@spiral:~/clients/cesium/cesium.com-next/pages]$ node
Welcome to Node.js v12.18.1.
Type ".help" for more information.
> const { utcToZonedTime } = require("date-fns-tz");
undefined
> utcToZonedTime("2000-01-01", "Europe/London")
2000-01-01T16:00:00.000Z               <---- why is this 4pm?
> utcToZonedTime("2000-01-01Z", "Europe/London")
2000-01-01T08:00:00.000Z               <---- why is this 8am?
> utcToZonedTime("2000-01-01T00:00:00Z", "Europe/London")
2000-01-01T08:00:00.000Z               <---- as above
> utcToZonedTime("2000-01-01T00:00:00+0000", "Europe/London")
2000-01-01T08:00:00.000Z               <---- as above
>
```

I don't know what to expect in the first case. Is it supposed to take the presented datetime as in my local time zone? If so the correct output would be 8am, not 4pm, as I am in America/Vancouver time. I don't know why it would be outputting 4pm. Is it supposed to assume the presented datetime is already UTC (as would make sense given the name `utcToZonedTime`)? If so the correct output would be midnight, since London time is the same as UTC in winter.

In the other cases, where I've specified my input as already being UTC, I expected midnight to come back out but am getting 8am.

**Comment by rhogeranacleto** [comment]
I have the same problem.
When I try to convert a date using a timezone like `America/Sao_Paulo` it returns the properly time, but with something like `Etc/GMT+3` (that is a valid timezone), it returns a wrong time.

![image](https://user-images.githubusercontent.com/4934413/102714566-22c4d600-42ae-11eb-8663-492fbb33407f.png)
it results in 
![image](https://user-images.githubusercontent.com/4934413/102714606-91a22f00-42ae-11eb-98b7-e42a4e4b0de3.png)

We can see the UTC hours (15h) is converted to 12h in the first one but not converted in the second one :thinking:

**Comment by LiadBerko** [comment]
Hello,
This lib is great! Thank you for that.

I am experiencing the same thing with some timezones, any ETA for a fix?

**Comment by VictoriaOtm** [comment]
Hello! Thank you for your awesome lib!
But here is one timezone which has a new offset value now - "Europe/Volgograd". It used to be UTC+4 but it has been changed for UTC+3
Could you update this please?

https://www.timeanddate.com/news/time/russia-volgograd-time-zone-2020.html#:~:text=On%20December%2016%2C%20the%20Russian,zone%20from%20December%2027%2C%202020.&text=On%20December%2027%2C%202020%2C%20at,%2C%20which%20is%20UTC%2B3.

**Comment by VictoriaOtm** [comment]
> So I don't think it's in scope for this library to address changes to regions' time zones. That's up to the browsers.

Well, I didn't notice, you're right, thanks!

**Comment by marnusw** [comment]
@DiagoSmith in your example you are using the timezone "MST". That is not in IANA timezone format and will not work.
@rhogeranacleto while that format might be valid but I'm not sure whether it qualifies as an IANA timezone that the Inlt library will parse (I may be wrong, perhaps the regex used for identifying IANA tzs in this lib doesn't match it). Either way it seems explicit support will need to be added for that. PR welcome.
@LiadBerko when you say "unsupported timezones" does that mean they are not being parsed / working at all? The supported timezone names are down to the Inlt API of the browser/platform you are using, this library does not contain any timezone data. To extent support to other tzs you will need to use a polyfill that does support them.

**Comment by marnusw** [comment]
This issue seems to center around time zones supported by the Intl API so I will close it. If there is a specific issue with the calculations at a supported time zone please open a new issue.
