### ISSUE TITLE
IE 11 | Option value 'AMERICA/NEW_YORK' for 'timeZone' is outside of valid range. Expected: ['UTC']

### ISSUE THREAD

**Issue by ritox842** [marnusw/date-fns-tz#96]
Hello.

I'm getting the following error only when using IE 11:
`Option value 'AMERICA/NEW_YORK' for 'timeZone' is outside of valid range. Expected: ['UTC']`

This is the associated code of mine:

```
    const newDate = typeof dateInput === 'string' ? utcToZonedTime(new Date(dateInput), 'UTC') : (dateInput as Date);
    date = utcToZonedTime(`${getDateISOString(newDate)}T00:00:00.000Z`, 'UTC');
```

I do use 'UTC' as my timezone but still getting timezone error.
The error is thrown from utcToZonedTime.

Any idea why it's happening and how to resolve it?

**Comment by mgalindo** [comment]
I am experiencing the same issue

**Comment by mahume** [comment]
Currently debugging this same issue. Breaking on ``utcToZonedTime``

Found this so far.
https://stackoverflow.com/questions/54364061/ie-11-throwing-timezone-is-outside-of-valid-range-when-setting-timezone-to

**Comment by aswinsekar** [comment]
IE doesn't support IANA timezones. We need to add polyfill for it.

Suggested [polyfill](https://github.com/formatjs/date-time-format-timezone) is mentioned in ReadMe.

**Comment by marnusw** [comment]
Thanks @aswinsekar

**Comment by japboy** [comment]
anyone could resolve this issue with polyfill.io?
